// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CallCarManager.proto

package com.weiwuu.protobuf;

public final class CallCarManagerProto {
  private CallCarManagerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_weiwuu_protobuf_CallCarManager_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_weiwuu_protobuf_CallCarManager_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024CallCarManager.proto\022\023com.weiwuu.proto" +
      "buf\"g\n\016CallCarManager\022\n\n\002id\030\001 \001(\005\022\014\n\004nam" +
      "e\030\002 \001(\t\022\013\n\003tel\030\003 \001(\t\022\017\n\007unionid\030\004 \001(\t\022\016\n" +
      "\006cityId\030\013 \001(\005\022\r\n\005check\030\025 \001(\005BR\n\023com.weiw" +
      "uu.protobufB\023CallCarManagerProtoP\001\240\001\001\242\002\003" +
      "WPB\252\002\032Weiwuu.Protobuf.KnownTypesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_weiwuu_protobuf_CallCarManager_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_weiwuu_protobuf_CallCarManager_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_weiwuu_protobuf_CallCarManager_descriptor,
        new String[] { "Id", "Name", "Tel", "Unionid", "CityId", "Check", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
