// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CallCar.proto

package com.weiwuu.protobuf;

/**
 * Protobuf type {@code com.weiwuu.protobuf.CallCar}
 *
 * <pre>
 * 约车
 * </pre>
 */
public  final class CallCar extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.weiwuu.protobuf.CallCar)
    CallCarOrBuilder {
  // Use CallCar.newBuilder() to construct.
  private CallCar(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CallCar() {
    id_ = 0;
    time_ = "";
    addrFrom_ = "";
    addrTo_ = "";
    wxuid_ = "";
    name_ = "";
    tel_ = "";
    status_ = 0;
    cityId_ = 0;
    bbid_ = "";
    bbtel_ = "";
    bbname_ = "";
    carnum_ = "";
    cartel_ = "";
    carname_ = "";
    cartype_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CallCar(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            time_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            addrFrom_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            addrTo_ = s;
            break;
          }
          case 90: {
            String s = input.readStringRequireUtf8();

            wxuid_ = s;
            break;
          }
          case 98: {
            String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 106: {
            String s = input.readStringRequireUtf8();

            tel_ = s;
            break;
          }
          case 168: {

            status_ = input.readInt32();
            break;
          }
          case 248: {

            cityId_ = input.readInt32();
            break;
          }
          case 330: {
            String s = input.readStringRequireUtf8();

            bbid_ = s;
            break;
          }
          case 338: {
            String s = input.readStringRequireUtf8();

            bbtel_ = s;
            break;
          }
          case 346: {
            String s = input.readStringRequireUtf8();

            bbname_ = s;
            break;
          }
          case 410: {
            String s = input.readStringRequireUtf8();

            carnum_ = s;
            break;
          }
          case 418: {
            String s = input.readStringRequireUtf8();

            cartel_ = s;
            break;
          }
          case 426: {
            String s = input.readStringRequireUtf8();

            carname_ = s;
            break;
          }
          case 434: {
            String s = input.readStringRequireUtf8();

            cartype_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CallCarProto.internal_static_com_weiwuu_protobuf_CallCar_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CallCarProto.internal_static_com_weiwuu_protobuf_CallCar_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CallCar.class, Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>optional int32 id = 1;</code>
   *
   * <pre>
   * 约车ID
   * </pre>
   */
  public int getId() {
    return id_;
  }

  public static final int TIME_FIELD_NUMBER = 2;
  private volatile Object time_;
  /**
   * <code>optional string time = 2;</code>
   *
   * <pre>
   * 约车时间
   * </pre>
   */
  public String getTime() {
    Object ref = time_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      time_ = s;
      return s;
    }
  }
  /**
   * <code>optional string time = 2;</code>
   *
   * <pre>
   * 约车时间
   * </pre>
   */
  public com.google.protobuf.ByteString
      getTimeBytes() {
    Object ref = time_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      time_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRFROM_FIELD_NUMBER = 3;
  private volatile Object addrFrom_;
  /**
   * <code>optional string addrFrom = 3;</code>
   *
   * <pre>
   * 上车地点
   * </pre>
   */
  public String getAddrFrom() {
    Object ref = addrFrom_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      addrFrom_ = s;
      return s;
    }
  }
  /**
   * <code>optional string addrFrom = 3;</code>
   *
   * <pre>
   * 上车地点
   * </pre>
   */
  public com.google.protobuf.ByteString
      getAddrFromBytes() {
    Object ref = addrFrom_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      addrFrom_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRTO_FIELD_NUMBER = 4;
  private volatile Object addrTo_;
  /**
   * <code>optional string addrTo = 4;</code>
   *
   * <pre>
   * 目的地点
   * </pre>
   */
  public String getAddrTo() {
    Object ref = addrTo_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      addrTo_ = s;
      return s;
    }
  }
  /**
   * <code>optional string addrTo = 4;</code>
   *
   * <pre>
   * 目的地点
   * </pre>
   */
  public com.google.protobuf.ByteString
      getAddrToBytes() {
    Object ref = addrTo_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      addrTo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WXUID_FIELD_NUMBER = 11;
  private volatile Object wxuid_;
  /**
   * <code>optional string wxuid = 11;</code>
   *
   * <pre>
   * 用户微信的unionid
   * </pre>
   */
  public String getWxuid() {
    Object ref = wxuid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      wxuid_ = s;
      return s;
    }
  }
  /**
   * <code>optional string wxuid = 11;</code>
   *
   * <pre>
   * 用户微信的unionid
   * </pre>
   */
  public com.google.protobuf.ByteString
      getWxuidBytes() {
    Object ref = wxuid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      wxuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 12;
  private volatile Object name_;
  /**
   * <code>optional string name = 12;</code>
   *
   * <pre>
   * 客户姓名
   * </pre>
   */
  public String getName() {
    Object ref = name_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 12;</code>
   *
   * <pre>
   * 客户姓名
   * </pre>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    Object ref = name_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEL_FIELD_NUMBER = 13;
  private volatile Object tel_;
  /**
   * <code>optional string tel = 13;</code>
   *
   * <pre>
   * 客户电话
   * </pre>
   */
  public String getTel() {
    Object ref = tel_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      tel_ = s;
      return s;
    }
  }
  /**
   * <code>optional string tel = 13;</code>
   *
   * <pre>
   * 客户电话
   * </pre>
   */
  public com.google.protobuf.ByteString
      getTelBytes() {
    Object ref = tel_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      tel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 21;
  private int status_;
  /**
   * <code>optional int32 status = 21;</code>
   *
   * <pre>
   * 约车状态  0：未派车，1：已派车，2：已取消
   * </pre>
   */
  public int getStatus() {
    return status_;
  }

  public static final int CITYID_FIELD_NUMBER = 31;
  private int cityId_;
  /**
   * <code>optional int32 cityId = 31;</code>
   *
   * <pre>
   *所在城市ID
   * </pre>
   */
  public int getCityId() {
    return cityId_;
  }

  public static final int BBID_FIELD_NUMBER = 41;
  private volatile Object bbid_;
  /**
   * <code>optional string bbid = 41;</code>
   *
   * <pre>
   *服务帮帮信息
   * 帮帮ID
   * </pre>
   */
  public String getBbid() {
    Object ref = bbid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      bbid_ = s;
      return s;
    }
  }
  /**
   * <code>optional string bbid = 41;</code>
   *
   * <pre>
   *服务帮帮信息
   * 帮帮ID
   * </pre>
   */
  public com.google.protobuf.ByteString
      getBbidBytes() {
    Object ref = bbid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      bbid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BBTEL_FIELD_NUMBER = 42;
  private volatile Object bbtel_;
  /**
   * <code>optional string bbtel = 42;</code>
   *
   * <pre>
   * 帮帮电话
   * </pre>
   */
  public String getBbtel() {
    Object ref = bbtel_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      bbtel_ = s;
      return s;
    }
  }
  /**
   * <code>optional string bbtel = 42;</code>
   *
   * <pre>
   * 帮帮电话
   * </pre>
   */
  public com.google.protobuf.ByteString
      getBbtelBytes() {
    Object ref = bbtel_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      bbtel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BBNAME_FIELD_NUMBER = 43;
  private volatile Object bbname_;
  /**
   * <code>optional string bbname = 43;</code>
   *
   * <pre>
   * 帮帮姓名
   * </pre>
   */
  public String getBbname() {
    Object ref = bbname_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      bbname_ = s;
      return s;
    }
  }
  /**
   * <code>optional string bbname = 43;</code>
   *
   * <pre>
   * 帮帮姓名
   * </pre>
   */
  public com.google.protobuf.ByteString
      getBbnameBytes() {
    Object ref = bbname_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      bbname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARNUM_FIELD_NUMBER = 51;
  private volatile Object carnum_;
  /**
   * <code>optional string carnum = 51;</code>
   *
   * <pre>
   *专车信息
   * 车牌号
   * </pre>
   */
  public String getCarnum() {
    Object ref = carnum_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      carnum_ = s;
      return s;
    }
  }
  /**
   * <code>optional string carnum = 51;</code>
   *
   * <pre>
   *专车信息
   * 车牌号
   * </pre>
   */
  public com.google.protobuf.ByteString
      getCarnumBytes() {
    Object ref = carnum_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      carnum_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARTEL_FIELD_NUMBER = 52;
  private volatile Object cartel_;
  /**
   * <code>optional string cartel = 52;</code>
   *
   * <pre>
   * 司机电话
   * </pre>
   */
  public String getCartel() {
    Object ref = cartel_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      cartel_ = s;
      return s;
    }
  }
  /**
   * <code>optional string cartel = 52;</code>
   *
   * <pre>
   * 司机电话
   * </pre>
   */
  public com.google.protobuf.ByteString
      getCartelBytes() {
    Object ref = cartel_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      cartel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARNAME_FIELD_NUMBER = 53;
  private volatile Object carname_;
  /**
   * <code>optional string carname = 53;</code>
   *
   * <pre>
   * 司机姓名
   * </pre>
   */
  public String getCarname() {
    Object ref = carname_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      carname_ = s;
      return s;
    }
  }
  /**
   * <code>optional string carname = 53;</code>
   *
   * <pre>
   * 司机姓名
   * </pre>
   */
  public com.google.protobuf.ByteString
      getCarnameBytes() {
    Object ref = carname_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      carname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARTYPE_FIELD_NUMBER = 54;
  private volatile Object cartype_;
  /**
   * <code>optional string cartype = 54;</code>
   *
   * <pre>
   * 专车型号
   * </pre>
   */
  public String getCartype() {
    Object ref = cartype_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      cartype_ = s;
      return s;
    }
  }
  /**
   * <code>optional string cartype = 54;</code>
   *
   * <pre>
   * 专车型号
   * </pre>
   */
  public com.google.protobuf.ByteString
      getCartypeBytes() {
    Object ref = cartype_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      cartype_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, time_);
    }
    if (!getAddrFromBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, addrFrom_);
    }
    if (!getAddrToBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, addrTo_);
    }
    if (!getWxuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 11, wxuid_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 12, name_);
    }
    if (!getTelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 13, tel_);
    }
    if (status_ != 0) {
      output.writeInt32(21, status_);
    }
    if (cityId_ != 0) {
      output.writeInt32(31, cityId_);
    }
    if (!getBbidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 41, bbid_);
    }
    if (!getBbtelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 42, bbtel_);
    }
    if (!getBbnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 43, bbname_);
    }
    if (!getCarnumBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 51, carnum_);
    }
    if (!getCartelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 52, cartel_);
    }
    if (!getCarnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 53, carname_);
    }
    if (!getCartypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 54, cartype_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, time_);
    }
    if (!getAddrFromBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, addrFrom_);
    }
    if (!getAddrToBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, addrTo_);
    }
    if (!getWxuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(11, wxuid_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(12, name_);
    }
    if (!getTelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(13, tel_);
    }
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(21, status_);
    }
    if (cityId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(31, cityId_);
    }
    if (!getBbidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(41, bbid_);
    }
    if (!getBbtelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(42, bbtel_);
    }
    if (!getBbnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(43, bbname_);
    }
    if (!getCarnumBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(51, carnum_);
    }
    if (!getCartelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(52, cartel_);
    }
    if (!getCarnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(53, carname_);
    }
    if (!getCartypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(54, cartype_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CallCar)) {
      return super.equals(obj);
    }
    CallCar other = (CallCar) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getTime()
        .equals(other.getTime());
    result = result && getAddrFrom()
        .equals(other.getAddrFrom());
    result = result && getAddrTo()
        .equals(other.getAddrTo());
    result = result && getWxuid()
        .equals(other.getWxuid());
    result = result && getName()
        .equals(other.getName());
    result = result && getTel()
        .equals(other.getTel());
    result = result && (getStatus()
        == other.getStatus());
    result = result && (getCityId()
        == other.getCityId());
    result = result && getBbid()
        .equals(other.getBbid());
    result = result && getBbtel()
        .equals(other.getBbtel());
    result = result && getBbname()
        .equals(other.getBbname());
    result = result && getCarnum()
        .equals(other.getCarnum());
    result = result && getCartel()
        .equals(other.getCartel());
    result = result && getCarname()
        .equals(other.getCarname());
    result = result && getCartype()
        .equals(other.getCartype());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + getTime().hashCode();
    hash = (37 * hash) + ADDRFROM_FIELD_NUMBER;
    hash = (53 * hash) + getAddrFrom().hashCode();
    hash = (37 * hash) + ADDRTO_FIELD_NUMBER;
    hash = (53 * hash) + getAddrTo().hashCode();
    hash = (37 * hash) + WXUID_FIELD_NUMBER;
    hash = (53 * hash) + getWxuid().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + TEL_FIELD_NUMBER;
    hash = (53 * hash) + getTel().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    hash = (37 * hash) + CITYID_FIELD_NUMBER;
    hash = (53 * hash) + getCityId();
    hash = (37 * hash) + BBID_FIELD_NUMBER;
    hash = (53 * hash) + getBbid().hashCode();
    hash = (37 * hash) + BBTEL_FIELD_NUMBER;
    hash = (53 * hash) + getBbtel().hashCode();
    hash = (37 * hash) + BBNAME_FIELD_NUMBER;
    hash = (53 * hash) + getBbname().hashCode();
    hash = (37 * hash) + CARNUM_FIELD_NUMBER;
    hash = (53 * hash) + getCarnum().hashCode();
    hash = (37 * hash) + CARTEL_FIELD_NUMBER;
    hash = (53 * hash) + getCartel().hashCode();
    hash = (37 * hash) + CARNAME_FIELD_NUMBER;
    hash = (53 * hash) + getCarname().hashCode();
    hash = (37 * hash) + CARTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getCartype().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CallCar parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CallCar parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CallCar parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CallCar parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CallCar parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static CallCar parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static CallCar parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static CallCar parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static CallCar parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static CallCar parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CallCar prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.weiwuu.protobuf.CallCar}
   *
   * <pre>
   * 约车
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.weiwuu.protobuf.CallCar)
      CallCarOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CallCarProto.internal_static_com_weiwuu_protobuf_CallCar_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CallCarProto.internal_static_com_weiwuu_protobuf_CallCar_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CallCar.class, Builder.class);
    }

    // Construct using com.weiwuu.protobuf.CallCar.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0;

      time_ = "";

      addrFrom_ = "";

      addrTo_ = "";

      wxuid_ = "";

      name_ = "";

      tel_ = "";

      status_ = 0;

      cityId_ = 0;

      bbid_ = "";

      bbtel_ = "";

      bbname_ = "";

      carnum_ = "";

      cartel_ = "";

      carname_ = "";

      cartype_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CallCarProto.internal_static_com_weiwuu_protobuf_CallCar_descriptor;
    }

    public CallCar getDefaultInstanceForType() {
      return CallCar.getDefaultInstance();
    }

    public CallCar build() {
      CallCar result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public CallCar buildPartial() {
      CallCar result = new CallCar(this);
      result.id_ = id_;
      result.time_ = time_;
      result.addrFrom_ = addrFrom_;
      result.addrTo_ = addrTo_;
      result.wxuid_ = wxuid_;
      result.name_ = name_;
      result.tel_ = tel_;
      result.status_ = status_;
      result.cityId_ = cityId_;
      result.bbid_ = bbid_;
      result.bbtel_ = bbtel_;
      result.bbname_ = bbname_;
      result.carnum_ = carnum_;
      result.cartel_ = cartel_;
      result.carname_ = carname_;
      result.cartype_ = cartype_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CallCar) {
        return mergeFrom((CallCar)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CallCar other) {
      if (other == CallCar.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getTime().isEmpty()) {
        time_ = other.time_;
        onChanged();
      }
      if (!other.getAddrFrom().isEmpty()) {
        addrFrom_ = other.addrFrom_;
        onChanged();
      }
      if (!other.getAddrTo().isEmpty()) {
        addrTo_ = other.addrTo_;
        onChanged();
      }
      if (!other.getWxuid().isEmpty()) {
        wxuid_ = other.wxuid_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getTel().isEmpty()) {
        tel_ = other.tel_;
        onChanged();
      }
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      if (other.getCityId() != 0) {
        setCityId(other.getCityId());
      }
      if (!other.getBbid().isEmpty()) {
        bbid_ = other.bbid_;
        onChanged();
      }
      if (!other.getBbtel().isEmpty()) {
        bbtel_ = other.bbtel_;
        onChanged();
      }
      if (!other.getBbname().isEmpty()) {
        bbname_ = other.bbname_;
        onChanged();
      }
      if (!other.getCarnum().isEmpty()) {
        carnum_ = other.carnum_;
        onChanged();
      }
      if (!other.getCartel().isEmpty()) {
        cartel_ = other.cartel_;
        onChanged();
      }
      if (!other.getCarname().isEmpty()) {
        carname_ = other.carname_;
        onChanged();
      }
      if (!other.getCartype().isEmpty()) {
        cartype_ = other.cartype_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CallCar parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CallCar) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     * 约车ID
     * </pre>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     * 约车ID
     * </pre>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     * 约车ID
     * </pre>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private Object time_ = "";
    /**
     * <code>optional string time = 2;</code>
     *
     * <pre>
     * 约车时间
     * </pre>
     */
    public String getTime() {
      Object ref = time_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        time_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string time = 2;</code>
     *
     * <pre>
     * 约车时间
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string time = 2;</code>
     *
     * <pre>
     * 约车时间
     * </pre>
     */
    public Builder setTime(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string time = 2;</code>
     *
     * <pre>
     * 约车时间
     * </pre>
     */
    public Builder clearTime() {
      
      time_ = getDefaultInstance().getTime();
      onChanged();
      return this;
    }
    /**
     * <code>optional string time = 2;</code>
     *
     * <pre>
     * 约车时间
     * </pre>
     */
    public Builder setTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      time_ = value;
      onChanged();
      return this;
    }

    private Object addrFrom_ = "";
    /**
     * <code>optional string addrFrom = 3;</code>
     *
     * <pre>
     * 上车地点
     * </pre>
     */
    public String getAddrFrom() {
      Object ref = addrFrom_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        addrFrom_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string addrFrom = 3;</code>
     *
     * <pre>
     * 上车地点
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAddrFromBytes() {
      Object ref = addrFrom_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        addrFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string addrFrom = 3;</code>
     *
     * <pre>
     * 上车地点
     * </pre>
     */
    public Builder setAddrFrom(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      addrFrom_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string addrFrom = 3;</code>
     *
     * <pre>
     * 上车地点
     * </pre>
     */
    public Builder clearAddrFrom() {
      
      addrFrom_ = getDefaultInstance().getAddrFrom();
      onChanged();
      return this;
    }
    /**
     * <code>optional string addrFrom = 3;</code>
     *
     * <pre>
     * 上车地点
     * </pre>
     */
    public Builder setAddrFromBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      addrFrom_ = value;
      onChanged();
      return this;
    }

    private Object addrTo_ = "";
    /**
     * <code>optional string addrTo = 4;</code>
     *
     * <pre>
     * 目的地点
     * </pre>
     */
    public String getAddrTo() {
      Object ref = addrTo_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        addrTo_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string addrTo = 4;</code>
     *
     * <pre>
     * 目的地点
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAddrToBytes() {
      Object ref = addrTo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        addrTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string addrTo = 4;</code>
     *
     * <pre>
     * 目的地点
     * </pre>
     */
    public Builder setAddrTo(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      addrTo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string addrTo = 4;</code>
     *
     * <pre>
     * 目的地点
     * </pre>
     */
    public Builder clearAddrTo() {
      
      addrTo_ = getDefaultInstance().getAddrTo();
      onChanged();
      return this;
    }
    /**
     * <code>optional string addrTo = 4;</code>
     *
     * <pre>
     * 目的地点
     * </pre>
     */
    public Builder setAddrToBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      addrTo_ = value;
      onChanged();
      return this;
    }

    private Object wxuid_ = "";
    /**
     * <code>optional string wxuid = 11;</code>
     *
     * <pre>
     * 用户微信的unionid
     * </pre>
     */
    public String getWxuid() {
      Object ref = wxuid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        wxuid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string wxuid = 11;</code>
     *
     * <pre>
     * 用户微信的unionid
     * </pre>
     */
    public com.google.protobuf.ByteString
        getWxuidBytes() {
      Object ref = wxuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        wxuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string wxuid = 11;</code>
     *
     * <pre>
     * 用户微信的unionid
     * </pre>
     */
    public Builder setWxuid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      wxuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string wxuid = 11;</code>
     *
     * <pre>
     * 用户微信的unionid
     * </pre>
     */
    public Builder clearWxuid() {
      
      wxuid_ = getDefaultInstance().getWxuid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string wxuid = 11;</code>
     *
     * <pre>
     * 用户微信的unionid
     * </pre>
     */
    public Builder setWxuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      wxuid_ = value;
      onChanged();
      return this;
    }

    private Object name_ = "";
    /**
     * <code>optional string name = 12;</code>
     *
     * <pre>
     * 客户姓名
     * </pre>
     */
    public String getName() {
      Object ref = name_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string name = 12;</code>
     *
     * <pre>
     * 客户姓名
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 12;</code>
     *
     * <pre>
     * 客户姓名
     * </pre>
     */
    public Builder setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 12;</code>
     *
     * <pre>
     * 客户姓名
     * </pre>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 12;</code>
     *
     * <pre>
     * 客户姓名
     * </pre>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private Object tel_ = "";
    /**
     * <code>optional string tel = 13;</code>
     *
     * <pre>
     * 客户电话
     * </pre>
     */
    public String getTel() {
      Object ref = tel_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tel_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string tel = 13;</code>
     *
     * <pre>
     * 客户电话
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTelBytes() {
      Object ref = tel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string tel = 13;</code>
     *
     * <pre>
     * 客户电话
     * </pre>
     */
    public Builder setTel(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string tel = 13;</code>
     *
     * <pre>
     * 客户电话
     * </pre>
     */
    public Builder clearTel() {
      
      tel_ = getDefaultInstance().getTel();
      onChanged();
      return this;
    }
    /**
     * <code>optional string tel = 13;</code>
     *
     * <pre>
     * 客户电话
     * </pre>
     */
    public Builder setTelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tel_ = value;
      onChanged();
      return this;
    }

    private int status_ ;
    /**
     * <code>optional int32 status = 21;</code>
     *
     * <pre>
     * 约车状态  0：未派车，1：已派车，2：已取消
     * </pre>
     */
    public int getStatus() {
      return status_;
    }
    /**
     * <code>optional int32 status = 21;</code>
     *
     * <pre>
     * 约车状态  0：未派车，1：已派车，2：已取消
     * </pre>
     */
    public Builder setStatus(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 status = 21;</code>
     *
     * <pre>
     * 约车状态  0：未派车，1：已派车，2：已取消
     * </pre>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private int cityId_ ;
    /**
     * <code>optional int32 cityId = 31;</code>
     *
     * <pre>
     *所在城市ID
     * </pre>
     */
    public int getCityId() {
      return cityId_;
    }
    /**
     * <code>optional int32 cityId = 31;</code>
     *
     * <pre>
     *所在城市ID
     * </pre>
     */
    public Builder setCityId(int value) {
      
      cityId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 cityId = 31;</code>
     *
     * <pre>
     *所在城市ID
     * </pre>
     */
    public Builder clearCityId() {
      
      cityId_ = 0;
      onChanged();
      return this;
    }

    private Object bbid_ = "";
    /**
     * <code>optional string bbid = 41;</code>
     *
     * <pre>
     *服务帮帮信息
     * 帮帮ID
     * </pre>
     */
    public String getBbid() {
      Object ref = bbid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bbid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string bbid = 41;</code>
     *
     * <pre>
     *服务帮帮信息
     * 帮帮ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getBbidBytes() {
      Object ref = bbid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bbid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string bbid = 41;</code>
     *
     * <pre>
     *服务帮帮信息
     * 帮帮ID
     * </pre>
     */
    public Builder setBbid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bbid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string bbid = 41;</code>
     *
     * <pre>
     *服务帮帮信息
     * 帮帮ID
     * </pre>
     */
    public Builder clearBbid() {
      
      bbid_ = getDefaultInstance().getBbid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string bbid = 41;</code>
     *
     * <pre>
     *服务帮帮信息
     * 帮帮ID
     * </pre>
     */
    public Builder setBbidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bbid_ = value;
      onChanged();
      return this;
    }

    private Object bbtel_ = "";
    /**
     * <code>optional string bbtel = 42;</code>
     *
     * <pre>
     * 帮帮电话
     * </pre>
     */
    public String getBbtel() {
      Object ref = bbtel_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bbtel_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string bbtel = 42;</code>
     *
     * <pre>
     * 帮帮电话
     * </pre>
     */
    public com.google.protobuf.ByteString
        getBbtelBytes() {
      Object ref = bbtel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bbtel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string bbtel = 42;</code>
     *
     * <pre>
     * 帮帮电话
     * </pre>
     */
    public Builder setBbtel(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bbtel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string bbtel = 42;</code>
     *
     * <pre>
     * 帮帮电话
     * </pre>
     */
    public Builder clearBbtel() {
      
      bbtel_ = getDefaultInstance().getBbtel();
      onChanged();
      return this;
    }
    /**
     * <code>optional string bbtel = 42;</code>
     *
     * <pre>
     * 帮帮电话
     * </pre>
     */
    public Builder setBbtelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bbtel_ = value;
      onChanged();
      return this;
    }

    private Object bbname_ = "";
    /**
     * <code>optional string bbname = 43;</code>
     *
     * <pre>
     * 帮帮姓名
     * </pre>
     */
    public String getBbname() {
      Object ref = bbname_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bbname_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string bbname = 43;</code>
     *
     * <pre>
     * 帮帮姓名
     * </pre>
     */
    public com.google.protobuf.ByteString
        getBbnameBytes() {
      Object ref = bbname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bbname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string bbname = 43;</code>
     *
     * <pre>
     * 帮帮姓名
     * </pre>
     */
    public Builder setBbname(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bbname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string bbname = 43;</code>
     *
     * <pre>
     * 帮帮姓名
     * </pre>
     */
    public Builder clearBbname() {
      
      bbname_ = getDefaultInstance().getBbname();
      onChanged();
      return this;
    }
    /**
     * <code>optional string bbname = 43;</code>
     *
     * <pre>
     * 帮帮姓名
     * </pre>
     */
    public Builder setBbnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bbname_ = value;
      onChanged();
      return this;
    }

    private Object carnum_ = "";
    /**
     * <code>optional string carnum = 51;</code>
     *
     * <pre>
     *专车信息
     * 车牌号
     * </pre>
     */
    public String getCarnum() {
      Object ref = carnum_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        carnum_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string carnum = 51;</code>
     *
     * <pre>
     *专车信息
     * 车牌号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCarnumBytes() {
      Object ref = carnum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        carnum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string carnum = 51;</code>
     *
     * <pre>
     *专车信息
     * 车牌号
     * </pre>
     */
    public Builder setCarnum(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      carnum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string carnum = 51;</code>
     *
     * <pre>
     *专车信息
     * 车牌号
     * </pre>
     */
    public Builder clearCarnum() {
      
      carnum_ = getDefaultInstance().getCarnum();
      onChanged();
      return this;
    }
    /**
     * <code>optional string carnum = 51;</code>
     *
     * <pre>
     *专车信息
     * 车牌号
     * </pre>
     */
    public Builder setCarnumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      carnum_ = value;
      onChanged();
      return this;
    }

    private Object cartel_ = "";
    /**
     * <code>optional string cartel = 52;</code>
     *
     * <pre>
     * 司机电话
     * </pre>
     */
    public String getCartel() {
      Object ref = cartel_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cartel_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string cartel = 52;</code>
     *
     * <pre>
     * 司机电话
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCartelBytes() {
      Object ref = cartel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cartel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string cartel = 52;</code>
     *
     * <pre>
     * 司机电话
     * </pre>
     */
    public Builder setCartel(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cartel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string cartel = 52;</code>
     *
     * <pre>
     * 司机电话
     * </pre>
     */
    public Builder clearCartel() {
      
      cartel_ = getDefaultInstance().getCartel();
      onChanged();
      return this;
    }
    /**
     * <code>optional string cartel = 52;</code>
     *
     * <pre>
     * 司机电话
     * </pre>
     */
    public Builder setCartelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cartel_ = value;
      onChanged();
      return this;
    }

    private Object carname_ = "";
    /**
     * <code>optional string carname = 53;</code>
     *
     * <pre>
     * 司机姓名
     * </pre>
     */
    public String getCarname() {
      Object ref = carname_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        carname_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string carname = 53;</code>
     *
     * <pre>
     * 司机姓名
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCarnameBytes() {
      Object ref = carname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        carname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string carname = 53;</code>
     *
     * <pre>
     * 司机姓名
     * </pre>
     */
    public Builder setCarname(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      carname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string carname = 53;</code>
     *
     * <pre>
     * 司机姓名
     * </pre>
     */
    public Builder clearCarname() {
      
      carname_ = getDefaultInstance().getCarname();
      onChanged();
      return this;
    }
    /**
     * <code>optional string carname = 53;</code>
     *
     * <pre>
     * 司机姓名
     * </pre>
     */
    public Builder setCarnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      carname_ = value;
      onChanged();
      return this;
    }

    private Object cartype_ = "";
    /**
     * <code>optional string cartype = 54;</code>
     *
     * <pre>
     * 专车型号
     * </pre>
     */
    public String getCartype() {
      Object ref = cartype_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cartype_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string cartype = 54;</code>
     *
     * <pre>
     * 专车型号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCartypeBytes() {
      Object ref = cartype_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cartype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string cartype = 54;</code>
     *
     * <pre>
     * 专车型号
     * </pre>
     */
    public Builder setCartype(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cartype_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string cartype = 54;</code>
     *
     * <pre>
     * 专车型号
     * </pre>
     */
    public Builder clearCartype() {
      
      cartype_ = getDefaultInstance().getCartype();
      onChanged();
      return this;
    }
    /**
     * <code>optional string cartype = 54;</code>
     *
     * <pre>
     * 专车型号
     * </pre>
     */
    public Builder setCartypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cartype_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.weiwuu.protobuf.CallCar)
  }

  // @@protoc_insertion_point(class_scope:com.weiwuu.protobuf.CallCar)
  private static final CallCar DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CallCar();
  }

  public static CallCar getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CallCar>
      PARSER = new com.google.protobuf.AbstractParser<CallCar>() {
    public CallCar parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new CallCar(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<CallCar> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CallCar> getParserForType() {
    return PARSER;
  }

  public CallCar getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

