// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CallCar.proto

package com.weiwuu.protobuf;

public final class CallCarProto {
  private CallCarProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_weiwuu_protobuf_CallCar_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_weiwuu_protobuf_CallCar_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rCallCar.proto\022\023com.weiwuu.protobuf\"\376\001\n" +
      "\007CallCar\022\n\n\002id\030\001 \001(\005\022\014\n\004time\030\002 \001(\t\022\020\n\010ad" +
      "drFrom\030\003 \001(\t\022\016\n\006addrTo\030\004 \001(\t\022\r\n\005wxuid\030\013 " +
      "\001(\t\022\014\n\004name\030\014 \001(\t\022\013\n\003tel\030\r \001(\t\022\016\n\006status" +
      "\030\025 \001(\005\022\016\n\006cityId\030\037 \001(\005\022\014\n\004bbid\030) \001(\t\022\r\n\005" +
      "bbtel\030* \001(\t\022\016\n\006bbname\030+ \001(\t\022\016\n\006carnum\0303 " +
      "\001(\t\022\016\n\006cartel\0304 \001(\t\022\017\n\007carname\0305 \001(\t\022\017\n\007" +
      "cartype\0306 \001(\tBK\n\023com.weiwuu.protobufB\014Ca" +
      "llCarProtoP\001\240\001\001\242\002\003WPB\252\002\032Weiwuu.Protobuf." +
      "KnownTypesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_weiwuu_protobuf_CallCar_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_weiwuu_protobuf_CallCar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_weiwuu_protobuf_CallCar_descriptor,
        new String[] { "Id", "Time", "AddrFrom", "AddrTo", "Wxuid", "Name", "Tel", "Status", "CityId", "Bbid", "Bbtel", "Bbname", "Carnum", "Cartel", "Carname", "Cartype", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
