// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GardenPriceNews.proto

package com.weiwuu.protobuf;

public final class GardenPriceNewsProto {
  private GardenPriceNewsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_weiwuu_protobuf_GardenPriceNews_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_weiwuu_protobuf_GardenPriceNews_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025GardenPriceNews.proto\022\023com.weiwuu.prot" +
      "obuf\"A\n\017GardenPriceNews\022\014\n\004date\030\001 \001(\t\022\017\n" +
      "\007caption\030\002 \001(\t\022\017\n\007content\030\003 \001(\tBS\n\023com.w" +
      "eiwuu.protobufB\024GardenPriceNewsProtoP\001\240\001" +
      "\001\242\002\003WPB\252\002\032Weiwuu.Protobuf.KnownTypesb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_weiwuu_protobuf_GardenPriceNews_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_weiwuu_protobuf_GardenPriceNews_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_weiwuu_protobuf_GardenPriceNews_descriptor,
        new String[] { "Date", "Caption", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
