// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GardenPriceView.proto

package com.weiwuu.protobuf;

public final class GardenPriceViewProto {
  private GardenPriceViewProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_weiwuu_protobuf_GardenPriceView_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_weiwuu_protobuf_GardenPriceView_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025GardenPriceView.proto\022\023com.weiwuu.prot" +
      "obuf\032\025GardenPriceItem.proto\032\025GardenPrice" +
      "News.proto\"\225\001\n\017GardenPriceView\022\020\n\010garden" +
      "Id\030\001 \001(\005\0227\n\tpriceList\030\002 \003(\0132$.com.weiwuu" +
      ".protobuf.GardenPriceItem\0227\n\tpriceNews\030\003" +
      " \003(\0132$.com.weiwuu.protobuf.GardenPriceNe" +
      "wsBS\n\023com.weiwuu.protobufB\024GardenPriceVi" +
      "ewProtoP\001\240\001\001\242\002\003WPB\252\002\032Weiwuu.Protobuf.Kno" +
      "wnTypesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          GardenPriceItemProto.getDescriptor(),
          GardenPriceNewsProto.getDescriptor(),
        }, assigner);
    internal_static_com_weiwuu_protobuf_GardenPriceView_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_weiwuu_protobuf_GardenPriceView_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_weiwuu_protobuf_GardenPriceView_descriptor,
        new String[] { "GardenId", "PriceList", "PriceNews", });
    GardenPriceItemProto.getDescriptor();
    GardenPriceNewsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
