// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewsTopic.proto

package com.weiwuu.protobuf;

public final class NewsTopicProto {
  private NewsTopicProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_weiwuu_protobuf_NewsTopic_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_weiwuu_protobuf_NewsTopic_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017NewsTopic.proto\022\023com.weiwuu.protobuf\"5" +
      "\n\tNewsTopic\022\n\n\002id\030\001 \001(\005\022\r\n\005topic\030\002 \001(\t\022\r" +
      "\n\005notes\030\003 \001(\tBM\n\023com.weiwuu.protobufB\016Ne" +
      "wsTopicProtoP\001\240\001\001\242\002\003WPB\252\002\032Weiwuu.Protobu" +
      "f.KnownTypesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_weiwuu_protobuf_NewsTopic_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_weiwuu_protobuf_NewsTopic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_weiwuu_protobuf_NewsTopic_descriptor,
        new String[] { "Id", "Topic", "Notes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
