// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewsTopic.proto

package com.weiwuu.protobuf;

/**
 * Protobuf type {@code com.weiwuu.protobuf.NewsTopic}
 *
 * <pre>
 * 消息主题
 * </pre>
 */
public  final class NewsTopic extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.weiwuu.protobuf.NewsTopic)
    NewsTopicOrBuilder {
  // Use NewsTopic.newBuilder() to construct.
  private NewsTopic(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private NewsTopic() {
    id_ = 0;
    topic_ = "";
    notes_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private NewsTopic(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            topic_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            notes_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return NewsTopicProto.internal_static_com_weiwuu_protobuf_NewsTopic_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return NewsTopicProto.internal_static_com_weiwuu_protobuf_NewsTopic_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            NewsTopic.class, Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>optional int32 id = 1;</code>
   *
   * <pre>
   * 主题ID
   * </pre>
   */
  public int getId() {
    return id_;
  }

  public static final int TOPIC_FIELD_NUMBER = 2;
  private volatile Object topic_;
  /**
   * <code>optional string topic = 2;</code>
   *
   * <pre>
   * 主题: (限制字数 &lt;= 16)
   * </pre>
   */
  public String getTopic() {
    Object ref = topic_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      topic_ = s;
      return s;
    }
  }
  /**
   * <code>optional string topic = 2;</code>
   *
   * <pre>
   * 主题: (限制字数 &lt;= 16)
   * </pre>
   */
  public com.google.protobuf.ByteString
      getTopicBytes() {
    Object ref = topic_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      topic_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOTES_FIELD_NUMBER = 3;
  private volatile Object notes_;
  /**
   * <code>optional string notes = 3;</code>
   *
   * <pre>
   * 说明: (限制字数 &lt;= 256)
   * </pre>
   */
  public String getNotes() {
    Object ref = notes_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      notes_ = s;
      return s;
    }
  }
  /**
   * <code>optional string notes = 3;</code>
   *
   * <pre>
   * 说明: (限制字数 &lt;= 256)
   * </pre>
   */
  public com.google.protobuf.ByteString
      getNotesBytes() {
    Object ref = notes_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      notes_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getTopicBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, topic_);
    }
    if (!getNotesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, notes_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getTopicBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, topic_);
    }
    if (!getNotesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, notes_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof NewsTopic)) {
      return super.equals(obj);
    }
    NewsTopic other = (NewsTopic) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getTopic()
        .equals(other.getTopic());
    result = result && getNotes()
        .equals(other.getNotes());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + TOPIC_FIELD_NUMBER;
    hash = (53 * hash) + getTopic().hashCode();
    hash = (37 * hash) + NOTES_FIELD_NUMBER;
    hash = (53 * hash) + getNotes().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static NewsTopic parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NewsTopic parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NewsTopic parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NewsTopic parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NewsTopic parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static NewsTopic parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static NewsTopic parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static NewsTopic parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static NewsTopic parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static NewsTopic parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(NewsTopic prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.weiwuu.protobuf.NewsTopic}
   *
   * <pre>
   * 消息主题
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.weiwuu.protobuf.NewsTopic)
      NewsTopicOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NewsTopicProto.internal_static_com_weiwuu_protobuf_NewsTopic_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NewsTopicProto.internal_static_com_weiwuu_protobuf_NewsTopic_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NewsTopic.class, Builder.class);
    }

    // Construct using com.weiwuu.protobuf.NewsTopic.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0;

      topic_ = "";

      notes_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return NewsTopicProto.internal_static_com_weiwuu_protobuf_NewsTopic_descriptor;
    }

    public NewsTopic getDefaultInstanceForType() {
      return NewsTopic.getDefaultInstance();
    }

    public NewsTopic build() {
      NewsTopic result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public NewsTopic buildPartial() {
      NewsTopic result = new NewsTopic(this);
      result.id_ = id_;
      result.topic_ = topic_;
      result.notes_ = notes_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof NewsTopic) {
        return mergeFrom((NewsTopic)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(NewsTopic other) {
      if (other == NewsTopic.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getTopic().isEmpty()) {
        topic_ = other.topic_;
        onChanged();
      }
      if (!other.getNotes().isEmpty()) {
        notes_ = other.notes_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      NewsTopic parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (NewsTopic) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     * 主题ID
     * </pre>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     * 主题ID
     * </pre>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     * 主题ID
     * </pre>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private Object topic_ = "";
    /**
     * <code>optional string topic = 2;</code>
     *
     * <pre>
     * 主题: (限制字数 &lt;= 16)
     * </pre>
     */
    public String getTopic() {
      Object ref = topic_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string topic = 2;</code>
     *
     * <pre>
     * 主题: (限制字数 &lt;= 16)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      Object ref = topic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string topic = 2;</code>
     *
     * <pre>
     * 主题: (限制字数 &lt;= 16)
     * </pre>
     */
    public Builder setTopic(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topic_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string topic = 2;</code>
     *
     * <pre>
     * 主题: (限制字数 &lt;= 16)
     * </pre>
     */
    public Builder clearTopic() {
      
      topic_ = getDefaultInstance().getTopic();
      onChanged();
      return this;
    }
    /**
     * <code>optional string topic = 2;</code>
     *
     * <pre>
     * 主题: (限制字数 &lt;= 16)
     * </pre>
     */
    public Builder setTopicBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topic_ = value;
      onChanged();
      return this;
    }

    private Object notes_ = "";
    /**
     * <code>optional string notes = 3;</code>
     *
     * <pre>
     * 说明: (限制字数 &lt;= 256)
     * </pre>
     */
    public String getNotes() {
      Object ref = notes_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        notes_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string notes = 3;</code>
     *
     * <pre>
     * 说明: (限制字数 &lt;= 256)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNotesBytes() {
      Object ref = notes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        notes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string notes = 3;</code>
     *
     * <pre>
     * 说明: (限制字数 &lt;= 256)
     * </pre>
     */
    public Builder setNotes(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      notes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string notes = 3;</code>
     *
     * <pre>
     * 说明: (限制字数 &lt;= 256)
     * </pre>
     */
    public Builder clearNotes() {
      
      notes_ = getDefaultInstance().getNotes();
      onChanged();
      return this;
    }
    /**
     * <code>optional string notes = 3;</code>
     *
     * <pre>
     * 说明: (限制字数 &lt;= 256)
     * </pre>
     */
    public Builder setNotesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      notes_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.weiwuu.protobuf.NewsTopic)
  }

  // @@protoc_insertion_point(class_scope:com.weiwuu.protobuf.NewsTopic)
  private static final NewsTopic DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new NewsTopic();
  }

  public static NewsTopic getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NewsTopic>
      PARSER = new com.google.protobuf.AbstractParser<NewsTopic>() {
    public NewsTopic parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new NewsTopic(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<NewsTopic> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<NewsTopic> getParserForType() {
    return PARSER;
  }

  public NewsTopic getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

