// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewsTag.proto

package com.weiwuu.protobuf;

public final class NewsTagProto {
  private NewsTagProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_weiwuu_protobuf_NewsTag_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_weiwuu_protobuf_NewsTag_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rNewsTag.proto\022\023com.weiwuu.protobuf\"1\n\007" +
      "NewsTag\022\n\n\002id\030\001 \001(\005\022\013\n\003tag\030\002 \001(\t\022\r\n\005note" +
      "s\030\003 \001(\tBK\n\023com.weiwuu.protobufB\014NewsTagP" +
      "rotoP\001\240\001\001\242\002\003WPB\252\002\032Weiwuu.Protobuf.KnownT" +
      "ypesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_weiwuu_protobuf_NewsTag_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_weiwuu_protobuf_NewsTag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_weiwuu_protobuf_NewsTag_descriptor,
        new String[] { "Id", "Tag", "Notes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
