// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: News.proto

package com.weiwuu.protobuf;

/**
 * Protobuf type {@code com.weiwuu.protobuf.News}
 *
 * <pre>
 * 消息
 * </pre>
 */
public  final class News extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.weiwuu.protobuf.News)
    NewsOrBuilder {
  // Use News.newBuilder() to construct.
  private News(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private News() {
    id_ = 0;
    issueTime_ = "";
    type1_ = 0;
    type2_ = 0;
    type3_ = 0;
    source_ = "";
    sourceURL_ = "";
    author_ = "";
    authorURL_ = "";
    caption_ = "";
    thumbURL_ = "";
    figureURL_ = "";
    content_ = "";
    description_ = "";
    shareDesc_ = "";
    tagIds_ = java.util.Collections.emptyList();
    topicIds_ = java.util.Collections.emptyList();
    relateIds_ = java.util.Collections.emptyList();
    rotate_ = false;
    cityId_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private News(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            issueTime_ = s;
            break;
          }
          case 32: {

            type1_ = input.readInt32();
            break;
          }
          case 40: {

            type2_ = input.readInt32();
            break;
          }
          case 48: {

            type3_ = input.readInt32();
            break;
          }
          case 82: {
            String s = input.readStringRequireUtf8();

            source_ = s;
            break;
          }
          case 90: {
            String s = input.readStringRequireUtf8();

            sourceURL_ = s;
            break;
          }
          case 98: {
            String s = input.readStringRequireUtf8();

            author_ = s;
            break;
          }
          case 106: {
            String s = input.readStringRequireUtf8();

            authorURL_ = s;
            break;
          }
          case 162: {
            String s = input.readStringRequireUtf8();

            caption_ = s;
            break;
          }
          case 170: {
            String s = input.readStringRequireUtf8();

            thumbURL_ = s;
            break;
          }
          case 178: {
            String s = input.readStringRequireUtf8();

            figureURL_ = s;
            break;
          }
          case 186: {
            String s = input.readStringRequireUtf8();

            content_ = s;
            break;
          }
          case 194: {
            String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 202: {
            String s = input.readStringRequireUtf8();

            shareDesc_ = s;
            break;
          }
          case 240: {
            if (!((mutable_bitField0_ & 0x00008000) == 0x00008000)) {
              tagIds_ = new java.util.ArrayList<Integer>();
              mutable_bitField0_ |= 0x00008000;
            }
            tagIds_.add(input.readInt32());
            break;
          }
          case 242: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00008000) == 0x00008000) && input.getBytesUntilLimit() > 0) {
              tagIds_ = new java.util.ArrayList<Integer>();
              mutable_bitField0_ |= 0x00008000;
            }
            while (input.getBytesUntilLimit() > 0) {
              tagIds_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 248: {
            if (!((mutable_bitField0_ & 0x00010000) == 0x00010000)) {
              topicIds_ = new java.util.ArrayList<Integer>();
              mutable_bitField0_ |= 0x00010000;
            }
            topicIds_.add(input.readInt32());
            break;
          }
          case 250: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00010000) == 0x00010000) && input.getBytesUntilLimit() > 0) {
              topicIds_ = new java.util.ArrayList<Integer>();
              mutable_bitField0_ |= 0x00010000;
            }
            while (input.getBytesUntilLimit() > 0) {
              topicIds_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 256: {
            if (!((mutable_bitField0_ & 0x00020000) == 0x00020000)) {
              relateIds_ = new java.util.ArrayList<Integer>();
              mutable_bitField0_ |= 0x00020000;
            }
            relateIds_.add(input.readInt32());
            break;
          }
          case 258: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00020000) == 0x00020000) && input.getBytesUntilLimit() > 0) {
              relateIds_ = new java.util.ArrayList<Integer>();
              mutable_bitField0_ |= 0x00020000;
            }
            while (input.getBytesUntilLimit() > 0) {
              relateIds_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 320: {

            rotate_ = input.readBool();
            break;
          }
          case 328: {

            cityId_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00008000) == 0x00008000)) {
        tagIds_ = java.util.Collections.unmodifiableList(tagIds_);
      }
      if (((mutable_bitField0_ & 0x00010000) == 0x00010000)) {
        topicIds_ = java.util.Collections.unmodifiableList(topicIds_);
      }
      if (((mutable_bitField0_ & 0x00020000) == 0x00020000)) {
        relateIds_ = java.util.Collections.unmodifiableList(relateIds_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return NewsProto.internal_static_com_weiwuu_protobuf_News_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return NewsProto.internal_static_com_weiwuu_protobuf_News_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            News.class, Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>optional int32 id = 1;</code>
   *
   * <pre>
   * ID
   * </pre>
   */
  public int getId() {
    return id_;
  }

  public static final int ISSUETIME_FIELD_NUMBER = 3;
  private volatile Object issueTime_;
  /**
   * <code>optional string issueTime = 3;</code>
   *
   * <pre>
   * 发布时间:  (yyyy-MM-dd hh:mm:dd)
   * </pre>
   */
  public String getIssueTime() {
    Object ref = issueTime_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      issueTime_ = s;
      return s;
    }
  }
  /**
   * <code>optional string issueTime = 3;</code>
   *
   * <pre>
   * 发布时间:  (yyyy-MM-dd hh:mm:dd)
   * </pre>
   */
  public com.google.protobuf.ByteString
      getIssueTimeBytes() {
    Object ref = issueTime_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      issueTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE1_FIELD_NUMBER = 4;
  private int type1_;
  /**
   * <code>optional int32 type1 = 4;</code>
   *
   * <pre>
   * 主要归类
   * </pre>
   */
  public int getType1() {
    return type1_;
  }

  public static final int TYPE2_FIELD_NUMBER = 5;
  private int type2_;
  /**
   * <code>optional int32 type2 = 5;</code>
   *
   * <pre>
   * 次要归类
   * </pre>
   */
  public int getType2() {
    return type2_;
  }

  public static final int TYPE3_FIELD_NUMBER = 6;
  private int type3_;
  /**
   * <code>optional int32 type3 = 6;</code>
   *
   * <pre>
   * 备选归类
   * </pre>
   */
  public int getType3() {
    return type3_;
  }

  public static final int SOURCE_FIELD_NUMBER = 10;
  private volatile Object source_;
  /**
   * <code>optional string source = 10;</code>
   *
   * <pre>
   * 来源: (限制字数 &lt;= 64)
   * </pre>
   */
  public String getSource() {
    Object ref = source_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      source_ = s;
      return s;
    }
  }
  /**
   * <code>optional string source = 10;</code>
   *
   * <pre>
   * 来源: (限制字数 &lt;= 64)
   * </pre>
   */
  public com.google.protobuf.ByteString
      getSourceBytes() {
    Object ref = source_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      source_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCEURL_FIELD_NUMBER = 11;
  private volatile Object sourceURL_;
  /**
   * <code>optional string sourceURL = 11;</code>
   */
  public String getSourceURL() {
    Object ref = sourceURL_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      sourceURL_ = s;
      return s;
    }
  }
  /**
   * <code>optional string sourceURL = 11;</code>
   */
  public com.google.protobuf.ByteString
      getSourceURLBytes() {
    Object ref = sourceURL_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      sourceURL_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUTHOR_FIELD_NUMBER = 12;
  private volatile Object author_;
  /**
   * <code>optional string author = 12;</code>
   *
   * <pre>
   * 作者: (限制字数 &lt;= 64)
   * </pre>
   */
  public String getAuthor() {
    Object ref = author_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      author_ = s;
      return s;
    }
  }
  /**
   * <code>optional string author = 12;</code>
   *
   * <pre>
   * 作者: (限制字数 &lt;= 64)
   * </pre>
   */
  public com.google.protobuf.ByteString
      getAuthorBytes() {
    Object ref = author_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      author_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUTHORURL_FIELD_NUMBER = 13;
  private volatile Object authorURL_;
  /**
   * <code>optional string authorURL = 13;</code>
   */
  public String getAuthorURL() {
    Object ref = authorURL_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      authorURL_ = s;
      return s;
    }
  }
  /**
   * <code>optional string authorURL = 13;</code>
   */
  public com.google.protobuf.ByteString
      getAuthorURLBytes() {
    Object ref = authorURL_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      authorURL_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAPTION_FIELD_NUMBER = 20;
  private volatile Object caption_;
  /**
   * <code>optional string caption = 20;</code>
   *
   * <pre>
   * 标题: (限制字数 &lt;= 64)
   * </pre>
   */
  public String getCaption() {
    Object ref = caption_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      caption_ = s;
      return s;
    }
  }
  /**
   * <code>optional string caption = 20;</code>
   *
   * <pre>
   * 标题: (限制字数 &lt;= 64)
   * </pre>
   */
  public com.google.protobuf.ByteString
      getCaptionBytes() {
    Object ref = caption_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      caption_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int THUMBURL_FIELD_NUMBER = 21;
  private volatile Object thumbURL_;
  /**
   * <code>optional string thumbURL = 21;</code>
   *
   * <pre>
   * 缩略图: (限制字数 &lt;= 256)
   * </pre>
   */
  public String getThumbURL() {
    Object ref = thumbURL_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      thumbURL_ = s;
      return s;
    }
  }
  /**
   * <code>optional string thumbURL = 21;</code>
   *
   * <pre>
   * 缩略图: (限制字数 &lt;= 256)
   * </pre>
   */
  public com.google.protobuf.ByteString
      getThumbURLBytes() {
    Object ref = thumbURL_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      thumbURL_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIGUREURL_FIELD_NUMBER = 22;
  private volatile Object figureURL_;
  /**
   * <code>optional string figureURL = 22;</code>
   *
   * <pre>
   * 主配图: (限制字数 &lt;= 256)
   * </pre>
   */
  public String getFigureURL() {
    Object ref = figureURL_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      figureURL_ = s;
      return s;
    }
  }
  /**
   * <code>optional string figureURL = 22;</code>
   *
   * <pre>
   * 主配图: (限制字数 &lt;= 256)
   * </pre>
   */
  public com.google.protobuf.ByteString
      getFigureURLBytes() {
    Object ref = figureURL_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      figureURL_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_FIELD_NUMBER = 23;
  private volatile Object content_;
  /**
   * <code>optional string content = 23;</code>
   *
   * <pre>
   * 内容: (限制字数 &lt;= 4096)
   * </pre>
   */
  public String getContent() {
    Object ref = content_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <code>optional string content = 23;</code>
   *
   * <pre>
   * 内容: (限制字数 &lt;= 4096)
   * </pre>
   */
  public com.google.protobuf.ByteString
      getContentBytes() {
    Object ref = content_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 24;
  private volatile Object description_;
  /**
   * <code>optional string description = 24;</code>
   *
   * <pre>
   * 内容摘要: (限制字数 &lt;= 200)
   * </pre>
   */
  public String getDescription() {
    Object ref = description_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>optional string description = 24;</code>
   *
   * <pre>
   * 内容摘要: (限制字数 &lt;= 200)
   * </pre>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    Object ref = description_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHAREDESC_FIELD_NUMBER = 25;
  private volatile Object shareDesc_;
  /**
   * <code>optional string shareDesc = 25;</code>
   *
   * <pre>
   * 分享描述: (限制字数 &lt;= 200)
   * </pre>
   */
  public String getShareDesc() {
    Object ref = shareDesc_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      shareDesc_ = s;
      return s;
    }
  }
  /**
   * <code>optional string shareDesc = 25;</code>
   *
   * <pre>
   * 分享描述: (限制字数 &lt;= 200)
   * </pre>
   */
  public com.google.protobuf.ByteString
      getShareDescBytes() {
    Object ref = shareDesc_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      shareDesc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TAGIDS_FIELD_NUMBER = 30;
  private java.util.List<Integer> tagIds_;
  /**
   * <code>repeated int32 tagIds = 30;</code>
   *
   * <pre>
   * 相关标签清单
   * </pre>
   */
  public java.util.List<Integer>
      getTagIdsList() {
    return tagIds_;
  }
  /**
   * <code>repeated int32 tagIds = 30;</code>
   *
   * <pre>
   * 相关标签清单
   * </pre>
   */
  public int getTagIdsCount() {
    return tagIds_.size();
  }
  /**
   * <code>repeated int32 tagIds = 30;</code>
   *
   * <pre>
   * 相关标签清单
   * </pre>
   */
  public int getTagIds(int index) {
    return tagIds_.get(index);
  }
  private int tagIdsMemoizedSerializedSize = -1;

  public static final int TOPICIDS_FIELD_NUMBER = 31;
  private java.util.List<Integer> topicIds_;
  /**
   * <code>repeated int32 topicIds = 31;</code>
   *
   * <pre>
   * 相关主题清单
   * </pre>
   */
  public java.util.List<Integer>
      getTopicIdsList() {
    return topicIds_;
  }
  /**
   * <code>repeated int32 topicIds = 31;</code>
   *
   * <pre>
   * 相关主题清单
   * </pre>
   */
  public int getTopicIdsCount() {
    return topicIds_.size();
  }
  /**
   * <code>repeated int32 topicIds = 31;</code>
   *
   * <pre>
   * 相关主题清单
   * </pre>
   */
  public int getTopicIds(int index) {
    return topicIds_.get(index);
  }
  private int topicIdsMemoizedSerializedSize = -1;

  public static final int RELATEIDS_FIELD_NUMBER = 32;
  private java.util.List<Integer> relateIds_;
  /**
   * <code>repeated int32 relateIds = 32;</code>
   *
   * <pre>
   * 相关新闻清单
   * </pre>
   */
  public java.util.List<Integer>
      getRelateIdsList() {
    return relateIds_;
  }
  /**
   * <code>repeated int32 relateIds = 32;</code>
   *
   * <pre>
   * 相关新闻清单
   * </pre>
   */
  public int getRelateIdsCount() {
    return relateIds_.size();
  }
  /**
   * <code>repeated int32 relateIds = 32;</code>
   *
   * <pre>
   * 相关新闻清单
   * </pre>
   */
  public int getRelateIds(int index) {
    return relateIds_.get(index);
  }
  private int relateIdsMemoizedSerializedSize = -1;

  public static final int ROTATE_FIELD_NUMBER = 40;
  private boolean rotate_;
  /**
   * <code>optional bool rotate = 40;</code>
   *
   * <pre>
   * 是否顶部轮播新闻   true:是，false：不是
   * </pre>
   */
  public boolean getRotate() {
    return rotate_;
  }

  public static final int CITYID_FIELD_NUMBER = 41;
  private int cityId_;
  /**
   * <code>optional int32 cityId = 41;</code>
   *
   * <pre>
   * 所属城市ID
   * </pre>
   */
  public int getCityId() {
    return cityId_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getIssueTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, issueTime_);
    }
    if (type1_ != 0) {
      output.writeInt32(4, type1_);
    }
    if (type2_ != 0) {
      output.writeInt32(5, type2_);
    }
    if (type3_ != 0) {
      output.writeInt32(6, type3_);
    }
    if (!getSourceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, source_);
    }
    if (!getSourceURLBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 11, sourceURL_);
    }
    if (!getAuthorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 12, author_);
    }
    if (!getAuthorURLBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 13, authorURL_);
    }
    if (!getCaptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 20, caption_);
    }
    if (!getThumbURLBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 21, thumbURL_);
    }
    if (!getFigureURLBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 22, figureURL_);
    }
    if (!getContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 23, content_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 24, description_);
    }
    if (!getShareDescBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 25, shareDesc_);
    }
    if (getTagIdsList().size() > 0) {
      output.writeRawVarint32(242);
      output.writeRawVarint32(tagIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < tagIds_.size(); i++) {
      output.writeInt32NoTag(tagIds_.get(i));
    }
    if (getTopicIdsList().size() > 0) {
      output.writeRawVarint32(250);
      output.writeRawVarint32(topicIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < topicIds_.size(); i++) {
      output.writeInt32NoTag(topicIds_.get(i));
    }
    if (getRelateIdsList().size() > 0) {
      output.writeRawVarint32(258);
      output.writeRawVarint32(relateIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < relateIds_.size(); i++) {
      output.writeInt32NoTag(relateIds_.get(i));
    }
    if (rotate_ != false) {
      output.writeBool(40, rotate_);
    }
    if (cityId_ != 0) {
      output.writeInt32(41, cityId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getIssueTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, issueTime_);
    }
    if (type1_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, type1_);
    }
    if (type2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, type2_);
    }
    if (type3_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, type3_);
    }
    if (!getSourceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, source_);
    }
    if (!getSourceURLBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(11, sourceURL_);
    }
    if (!getAuthorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(12, author_);
    }
    if (!getAuthorURLBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(13, authorURL_);
    }
    if (!getCaptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(20, caption_);
    }
    if (!getThumbURLBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(21, thumbURL_);
    }
    if (!getFigureURLBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(22, figureURL_);
    }
    if (!getContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(23, content_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(24, description_);
    }
    if (!getShareDescBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(25, shareDesc_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < tagIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(tagIds_.get(i));
      }
      size += dataSize;
      if (!getTagIdsList().isEmpty()) {
        size += 2;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      tagIdsMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < topicIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(topicIds_.get(i));
      }
      size += dataSize;
      if (!getTopicIdsList().isEmpty()) {
        size += 2;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      topicIdsMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < relateIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(relateIds_.get(i));
      }
      size += dataSize;
      if (!getRelateIdsList().isEmpty()) {
        size += 2;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      relateIdsMemoizedSerializedSize = dataSize;
    }
    if (rotate_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(40, rotate_);
    }
    if (cityId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(41, cityId_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof News)) {
      return super.equals(obj);
    }
    News other = (News) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getIssueTime()
        .equals(other.getIssueTime());
    result = result && (getType1()
        == other.getType1());
    result = result && (getType2()
        == other.getType2());
    result = result && (getType3()
        == other.getType3());
    result = result && getSource()
        .equals(other.getSource());
    result = result && getSourceURL()
        .equals(other.getSourceURL());
    result = result && getAuthor()
        .equals(other.getAuthor());
    result = result && getAuthorURL()
        .equals(other.getAuthorURL());
    result = result && getCaption()
        .equals(other.getCaption());
    result = result && getThumbURL()
        .equals(other.getThumbURL());
    result = result && getFigureURL()
        .equals(other.getFigureURL());
    result = result && getContent()
        .equals(other.getContent());
    result = result && getDescription()
        .equals(other.getDescription());
    result = result && getShareDesc()
        .equals(other.getShareDesc());
    result = result && getTagIdsList()
        .equals(other.getTagIdsList());
    result = result && getTopicIdsList()
        .equals(other.getTopicIdsList());
    result = result && getRelateIdsList()
        .equals(other.getRelateIdsList());
    result = result && (getRotate()
        == other.getRotate());
    result = result && (getCityId()
        == other.getCityId());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + ISSUETIME_FIELD_NUMBER;
    hash = (53 * hash) + getIssueTime().hashCode();
    hash = (37 * hash) + TYPE1_FIELD_NUMBER;
    hash = (53 * hash) + getType1();
    hash = (37 * hash) + TYPE2_FIELD_NUMBER;
    hash = (53 * hash) + getType2();
    hash = (37 * hash) + TYPE3_FIELD_NUMBER;
    hash = (53 * hash) + getType3();
    hash = (37 * hash) + SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getSource().hashCode();
    hash = (37 * hash) + SOURCEURL_FIELD_NUMBER;
    hash = (53 * hash) + getSourceURL().hashCode();
    hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
    hash = (53 * hash) + getAuthor().hashCode();
    hash = (37 * hash) + AUTHORURL_FIELD_NUMBER;
    hash = (53 * hash) + getAuthorURL().hashCode();
    hash = (37 * hash) + CAPTION_FIELD_NUMBER;
    hash = (53 * hash) + getCaption().hashCode();
    hash = (37 * hash) + THUMBURL_FIELD_NUMBER;
    hash = (53 * hash) + getThumbURL().hashCode();
    hash = (37 * hash) + FIGUREURL_FIELD_NUMBER;
    hash = (53 * hash) + getFigureURL().hashCode();
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + SHAREDESC_FIELD_NUMBER;
    hash = (53 * hash) + getShareDesc().hashCode();
    if (getTagIdsCount() > 0) {
      hash = (37 * hash) + TAGIDS_FIELD_NUMBER;
      hash = (53 * hash) + getTagIdsList().hashCode();
    }
    if (getTopicIdsCount() > 0) {
      hash = (37 * hash) + TOPICIDS_FIELD_NUMBER;
      hash = (53 * hash) + getTopicIdsList().hashCode();
    }
    if (getRelateIdsCount() > 0) {
      hash = (37 * hash) + RELATEIDS_FIELD_NUMBER;
      hash = (53 * hash) + getRelateIdsList().hashCode();
    }
    hash = (37 * hash) + ROTATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRotate());
    hash = (37 * hash) + CITYID_FIELD_NUMBER;
    hash = (53 * hash) + getCityId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static News parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static News parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static News parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static News parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static News parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static News parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static News parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static News parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static News parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static News parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(News prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.weiwuu.protobuf.News}
   *
   * <pre>
   * 消息
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.weiwuu.protobuf.News)
      NewsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NewsProto.internal_static_com_weiwuu_protobuf_News_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NewsProto.internal_static_com_weiwuu_protobuf_News_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              News.class, Builder.class);
    }

    // Construct using com.weiwuu.protobuf.News.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0;

      issueTime_ = "";

      type1_ = 0;

      type2_ = 0;

      type3_ = 0;

      source_ = "";

      sourceURL_ = "";

      author_ = "";

      authorURL_ = "";

      caption_ = "";

      thumbURL_ = "";

      figureURL_ = "";

      content_ = "";

      description_ = "";

      shareDesc_ = "";

      tagIds_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00008000);
      topicIds_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00010000);
      relateIds_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00020000);
      rotate_ = false;

      cityId_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return NewsProto.internal_static_com_weiwuu_protobuf_News_descriptor;
    }

    public News getDefaultInstanceForType() {
      return News.getDefaultInstance();
    }

    public News build() {
      News result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public News buildPartial() {
      News result = new News(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.issueTime_ = issueTime_;
      result.type1_ = type1_;
      result.type2_ = type2_;
      result.type3_ = type3_;
      result.source_ = source_;
      result.sourceURL_ = sourceURL_;
      result.author_ = author_;
      result.authorURL_ = authorURL_;
      result.caption_ = caption_;
      result.thumbURL_ = thumbURL_;
      result.figureURL_ = figureURL_;
      result.content_ = content_;
      result.description_ = description_;
      result.shareDesc_ = shareDesc_;
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        tagIds_ = java.util.Collections.unmodifiableList(tagIds_);
        bitField0_ = (bitField0_ & ~0x00008000);
      }
      result.tagIds_ = tagIds_;
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        topicIds_ = java.util.Collections.unmodifiableList(topicIds_);
        bitField0_ = (bitField0_ & ~0x00010000);
      }
      result.topicIds_ = topicIds_;
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        relateIds_ = java.util.Collections.unmodifiableList(relateIds_);
        bitField0_ = (bitField0_ & ~0x00020000);
      }
      result.relateIds_ = relateIds_;
      result.rotate_ = rotate_;
      result.cityId_ = cityId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof News) {
        return mergeFrom((News)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(News other) {
      if (other == News.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getIssueTime().isEmpty()) {
        issueTime_ = other.issueTime_;
        onChanged();
      }
      if (other.getType1() != 0) {
        setType1(other.getType1());
      }
      if (other.getType2() != 0) {
        setType2(other.getType2());
      }
      if (other.getType3() != 0) {
        setType3(other.getType3());
      }
      if (!other.getSource().isEmpty()) {
        source_ = other.source_;
        onChanged();
      }
      if (!other.getSourceURL().isEmpty()) {
        sourceURL_ = other.sourceURL_;
        onChanged();
      }
      if (!other.getAuthor().isEmpty()) {
        author_ = other.author_;
        onChanged();
      }
      if (!other.getAuthorURL().isEmpty()) {
        authorURL_ = other.authorURL_;
        onChanged();
      }
      if (!other.getCaption().isEmpty()) {
        caption_ = other.caption_;
        onChanged();
      }
      if (!other.getThumbURL().isEmpty()) {
        thumbURL_ = other.thumbURL_;
        onChanged();
      }
      if (!other.getFigureURL().isEmpty()) {
        figureURL_ = other.figureURL_;
        onChanged();
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.getShareDesc().isEmpty()) {
        shareDesc_ = other.shareDesc_;
        onChanged();
      }
      if (!other.tagIds_.isEmpty()) {
        if (tagIds_.isEmpty()) {
          tagIds_ = other.tagIds_;
          bitField0_ = (bitField0_ & ~0x00008000);
        } else {
          ensureTagIdsIsMutable();
          tagIds_.addAll(other.tagIds_);
        }
        onChanged();
      }
      if (!other.topicIds_.isEmpty()) {
        if (topicIds_.isEmpty()) {
          topicIds_ = other.topicIds_;
          bitField0_ = (bitField0_ & ~0x00010000);
        } else {
          ensureTopicIdsIsMutable();
          topicIds_.addAll(other.topicIds_);
        }
        onChanged();
      }
      if (!other.relateIds_.isEmpty()) {
        if (relateIds_.isEmpty()) {
          relateIds_ = other.relateIds_;
          bitField0_ = (bitField0_ & ~0x00020000);
        } else {
          ensureRelateIdsIsMutable();
          relateIds_.addAll(other.relateIds_);
        }
        onChanged();
      }
      if (other.getRotate() != false) {
        setRotate(other.getRotate());
      }
      if (other.getCityId() != 0) {
        setCityId(other.getCityId());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      News parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (News) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     * ID
     * </pre>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     * ID
     * </pre>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     * ID
     * </pre>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private Object issueTime_ = "";
    /**
     * <code>optional string issueTime = 3;</code>
     *
     * <pre>
     * 发布时间:  (yyyy-MM-dd hh:mm:dd)
     * </pre>
     */
    public String getIssueTime() {
      Object ref = issueTime_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        issueTime_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string issueTime = 3;</code>
     *
     * <pre>
     * 发布时间:  (yyyy-MM-dd hh:mm:dd)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIssueTimeBytes() {
      Object ref = issueTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        issueTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string issueTime = 3;</code>
     *
     * <pre>
     * 发布时间:  (yyyy-MM-dd hh:mm:dd)
     * </pre>
     */
    public Builder setIssueTime(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      issueTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string issueTime = 3;</code>
     *
     * <pre>
     * 发布时间:  (yyyy-MM-dd hh:mm:dd)
     * </pre>
     */
    public Builder clearIssueTime() {
      
      issueTime_ = getDefaultInstance().getIssueTime();
      onChanged();
      return this;
    }
    /**
     * <code>optional string issueTime = 3;</code>
     *
     * <pre>
     * 发布时间:  (yyyy-MM-dd hh:mm:dd)
     * </pre>
     */
    public Builder setIssueTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      issueTime_ = value;
      onChanged();
      return this;
    }

    private int type1_ ;
    /**
     * <code>optional int32 type1 = 4;</code>
     *
     * <pre>
     * 主要归类
     * </pre>
     */
    public int getType1() {
      return type1_;
    }
    /**
     * <code>optional int32 type1 = 4;</code>
     *
     * <pre>
     * 主要归类
     * </pre>
     */
    public Builder setType1(int value) {
      
      type1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 type1 = 4;</code>
     *
     * <pre>
     * 主要归类
     * </pre>
     */
    public Builder clearType1() {
      
      type1_ = 0;
      onChanged();
      return this;
    }

    private int type2_ ;
    /**
     * <code>optional int32 type2 = 5;</code>
     *
     * <pre>
     * 次要归类
     * </pre>
     */
    public int getType2() {
      return type2_;
    }
    /**
     * <code>optional int32 type2 = 5;</code>
     *
     * <pre>
     * 次要归类
     * </pre>
     */
    public Builder setType2(int value) {
      
      type2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 type2 = 5;</code>
     *
     * <pre>
     * 次要归类
     * </pre>
     */
    public Builder clearType2() {
      
      type2_ = 0;
      onChanged();
      return this;
    }

    private int type3_ ;
    /**
     * <code>optional int32 type3 = 6;</code>
     *
     * <pre>
     * 备选归类
     * </pre>
     */
    public int getType3() {
      return type3_;
    }
    /**
     * <code>optional int32 type3 = 6;</code>
     *
     * <pre>
     * 备选归类
     * </pre>
     */
    public Builder setType3(int value) {
      
      type3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 type3 = 6;</code>
     *
     * <pre>
     * 备选归类
     * </pre>
     */
    public Builder clearType3() {
      
      type3_ = 0;
      onChanged();
      return this;
    }

    private Object source_ = "";
    /**
     * <code>optional string source = 10;</code>
     *
     * <pre>
     * 来源: (限制字数 &lt;= 64)
     * </pre>
     */
    public String getSource() {
      Object ref = source_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        source_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string source = 10;</code>
     *
     * <pre>
     * 来源: (限制字数 &lt;= 64)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      Object ref = source_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string source = 10;</code>
     *
     * <pre>
     * 来源: (限制字数 &lt;= 64)
     * </pre>
     */
    public Builder setSource(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      source_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string source = 10;</code>
     *
     * <pre>
     * 来源: (限制字数 &lt;= 64)
     * </pre>
     */
    public Builder clearSource() {
      
      source_ = getDefaultInstance().getSource();
      onChanged();
      return this;
    }
    /**
     * <code>optional string source = 10;</code>
     *
     * <pre>
     * 来源: (限制字数 &lt;= 64)
     * </pre>
     */
    public Builder setSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      source_ = value;
      onChanged();
      return this;
    }

    private Object sourceURL_ = "";
    /**
     * <code>optional string sourceURL = 11;</code>
     */
    public String getSourceURL() {
      Object ref = sourceURL_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sourceURL_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string sourceURL = 11;</code>
     */
    public com.google.protobuf.ByteString
        getSourceURLBytes() {
      Object ref = sourceURL_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sourceURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sourceURL = 11;</code>
     */
    public Builder setSourceURL(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceURL_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sourceURL = 11;</code>
     */
    public Builder clearSourceURL() {
      
      sourceURL_ = getDefaultInstance().getSourceURL();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sourceURL = 11;</code>
     */
    public Builder setSourceURLBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceURL_ = value;
      onChanged();
      return this;
    }

    private Object author_ = "";
    /**
     * <code>optional string author = 12;</code>
     *
     * <pre>
     * 作者: (限制字数 &lt;= 64)
     * </pre>
     */
    public String getAuthor() {
      Object ref = author_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        author_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string author = 12;</code>
     *
     * <pre>
     * 作者: (限制字数 &lt;= 64)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAuthorBytes() {
      Object ref = author_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        author_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string author = 12;</code>
     *
     * <pre>
     * 作者: (限制字数 &lt;= 64)
     * </pre>
     */
    public Builder setAuthor(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      author_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string author = 12;</code>
     *
     * <pre>
     * 作者: (限制字数 &lt;= 64)
     * </pre>
     */
    public Builder clearAuthor() {
      
      author_ = getDefaultInstance().getAuthor();
      onChanged();
      return this;
    }
    /**
     * <code>optional string author = 12;</code>
     *
     * <pre>
     * 作者: (限制字数 &lt;= 64)
     * </pre>
     */
    public Builder setAuthorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      author_ = value;
      onChanged();
      return this;
    }

    private Object authorURL_ = "";
    /**
     * <code>optional string authorURL = 13;</code>
     */
    public String getAuthorURL() {
      Object ref = authorURL_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        authorURL_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string authorURL = 13;</code>
     */
    public com.google.protobuf.ByteString
        getAuthorURLBytes() {
      Object ref = authorURL_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        authorURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string authorURL = 13;</code>
     */
    public Builder setAuthorURL(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      authorURL_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string authorURL = 13;</code>
     */
    public Builder clearAuthorURL() {
      
      authorURL_ = getDefaultInstance().getAuthorURL();
      onChanged();
      return this;
    }
    /**
     * <code>optional string authorURL = 13;</code>
     */
    public Builder setAuthorURLBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      authorURL_ = value;
      onChanged();
      return this;
    }

    private Object caption_ = "";
    /**
     * <code>optional string caption = 20;</code>
     *
     * <pre>
     * 标题: (限制字数 &lt;= 64)
     * </pre>
     */
    public String getCaption() {
      Object ref = caption_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        caption_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string caption = 20;</code>
     *
     * <pre>
     * 标题: (限制字数 &lt;= 64)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCaptionBytes() {
      Object ref = caption_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        caption_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string caption = 20;</code>
     *
     * <pre>
     * 标题: (限制字数 &lt;= 64)
     * </pre>
     */
    public Builder setCaption(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      caption_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string caption = 20;</code>
     *
     * <pre>
     * 标题: (限制字数 &lt;= 64)
     * </pre>
     */
    public Builder clearCaption() {
      
      caption_ = getDefaultInstance().getCaption();
      onChanged();
      return this;
    }
    /**
     * <code>optional string caption = 20;</code>
     *
     * <pre>
     * 标题: (限制字数 &lt;= 64)
     * </pre>
     */
    public Builder setCaptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      caption_ = value;
      onChanged();
      return this;
    }

    private Object thumbURL_ = "";
    /**
     * <code>optional string thumbURL = 21;</code>
     *
     * <pre>
     * 缩略图: (限制字数 &lt;= 256)
     * </pre>
     */
    public String getThumbURL() {
      Object ref = thumbURL_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        thumbURL_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string thumbURL = 21;</code>
     *
     * <pre>
     * 缩略图: (限制字数 &lt;= 256)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getThumbURLBytes() {
      Object ref = thumbURL_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        thumbURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string thumbURL = 21;</code>
     *
     * <pre>
     * 缩略图: (限制字数 &lt;= 256)
     * </pre>
     */
    public Builder setThumbURL(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      thumbURL_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string thumbURL = 21;</code>
     *
     * <pre>
     * 缩略图: (限制字数 &lt;= 256)
     * </pre>
     */
    public Builder clearThumbURL() {
      
      thumbURL_ = getDefaultInstance().getThumbURL();
      onChanged();
      return this;
    }
    /**
     * <code>optional string thumbURL = 21;</code>
     *
     * <pre>
     * 缩略图: (限制字数 &lt;= 256)
     * </pre>
     */
    public Builder setThumbURLBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      thumbURL_ = value;
      onChanged();
      return this;
    }

    private Object figureURL_ = "";
    /**
     * <code>optional string figureURL = 22;</code>
     *
     * <pre>
     * 主配图: (限制字数 &lt;= 256)
     * </pre>
     */
    public String getFigureURL() {
      Object ref = figureURL_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        figureURL_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string figureURL = 22;</code>
     *
     * <pre>
     * 主配图: (限制字数 &lt;= 256)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getFigureURLBytes() {
      Object ref = figureURL_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        figureURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string figureURL = 22;</code>
     *
     * <pre>
     * 主配图: (限制字数 &lt;= 256)
     * </pre>
     */
    public Builder setFigureURL(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      figureURL_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string figureURL = 22;</code>
     *
     * <pre>
     * 主配图: (限制字数 &lt;= 256)
     * </pre>
     */
    public Builder clearFigureURL() {
      
      figureURL_ = getDefaultInstance().getFigureURL();
      onChanged();
      return this;
    }
    /**
     * <code>optional string figureURL = 22;</code>
     *
     * <pre>
     * 主配图: (限制字数 &lt;= 256)
     * </pre>
     */
    public Builder setFigureURLBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      figureURL_ = value;
      onChanged();
      return this;
    }

    private Object content_ = "";
    /**
     * <code>optional string content = 23;</code>
     *
     * <pre>
     * 内容: (限制字数 &lt;= 4096)
     * </pre>
     */
    public String getContent() {
      Object ref = content_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string content = 23;</code>
     *
     * <pre>
     * 内容: (限制字数 &lt;= 4096)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string content = 23;</code>
     *
     * <pre>
     * 内容: (限制字数 &lt;= 4096)
     * </pre>
     */
    public Builder setContent(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string content = 23;</code>
     *
     * <pre>
     * 内容: (限制字数 &lt;= 4096)
     * </pre>
     */
    public Builder clearContent() {
      
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }
    /**
     * <code>optional string content = 23;</code>
     *
     * <pre>
     * 内容: (限制字数 &lt;= 4096)
     * </pre>
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      content_ = value;
      onChanged();
      return this;
    }

    private Object description_ = "";
    /**
     * <code>optional string description = 24;</code>
     *
     * <pre>
     * 内容摘要: (限制字数 &lt;= 200)
     * </pre>
     */
    public String getDescription() {
      Object ref = description_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string description = 24;</code>
     *
     * <pre>
     * 内容摘要: (限制字数 &lt;= 200)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string description = 24;</code>
     *
     * <pre>
     * 内容摘要: (限制字数 &lt;= 200)
     * </pre>
     */
    public Builder setDescription(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string description = 24;</code>
     *
     * <pre>
     * 内容摘要: (限制字数 &lt;= 200)
     * </pre>
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>optional string description = 24;</code>
     *
     * <pre>
     * 内容摘要: (限制字数 &lt;= 200)
     * </pre>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private Object shareDesc_ = "";
    /**
     * <code>optional string shareDesc = 25;</code>
     *
     * <pre>
     * 分享描述: (限制字数 &lt;= 200)
     * </pre>
     */
    public String getShareDesc() {
      Object ref = shareDesc_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        shareDesc_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string shareDesc = 25;</code>
     *
     * <pre>
     * 分享描述: (限制字数 &lt;= 200)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getShareDescBytes() {
      Object ref = shareDesc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        shareDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string shareDesc = 25;</code>
     *
     * <pre>
     * 分享描述: (限制字数 &lt;= 200)
     * </pre>
     */
    public Builder setShareDesc(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      shareDesc_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string shareDesc = 25;</code>
     *
     * <pre>
     * 分享描述: (限制字数 &lt;= 200)
     * </pre>
     */
    public Builder clearShareDesc() {
      
      shareDesc_ = getDefaultInstance().getShareDesc();
      onChanged();
      return this;
    }
    /**
     * <code>optional string shareDesc = 25;</code>
     *
     * <pre>
     * 分享描述: (限制字数 &lt;= 200)
     * </pre>
     */
    public Builder setShareDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      shareDesc_ = value;
      onChanged();
      return this;
    }

    private java.util.List<Integer> tagIds_ = java.util.Collections.emptyList();
    private void ensureTagIdsIsMutable() {
      if (!((bitField0_ & 0x00008000) == 0x00008000)) {
        tagIds_ = new java.util.ArrayList<Integer>(tagIds_);
        bitField0_ |= 0x00008000;
       }
    }
    /**
     * <code>repeated int32 tagIds = 30;</code>
     *
     * <pre>
     * 相关标签清单
     * </pre>
     */
    public java.util.List<Integer>
        getTagIdsList() {
      return java.util.Collections.unmodifiableList(tagIds_);
    }
    /**
     * <code>repeated int32 tagIds = 30;</code>
     *
     * <pre>
     * 相关标签清单
     * </pre>
     */
    public int getTagIdsCount() {
      return tagIds_.size();
    }
    /**
     * <code>repeated int32 tagIds = 30;</code>
     *
     * <pre>
     * 相关标签清单
     * </pre>
     */
    public int getTagIds(int index) {
      return tagIds_.get(index);
    }
    /**
     * <code>repeated int32 tagIds = 30;</code>
     *
     * <pre>
     * 相关标签清单
     * </pre>
     */
    public Builder setTagIds(
        int index, int value) {
      ensureTagIdsIsMutable();
      tagIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 tagIds = 30;</code>
     *
     * <pre>
     * 相关标签清单
     * </pre>
     */
    public Builder addTagIds(int value) {
      ensureTagIdsIsMutable();
      tagIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 tagIds = 30;</code>
     *
     * <pre>
     * 相关标签清单
     * </pre>
     */
    public Builder addAllTagIds(
        Iterable<? extends Integer> values) {
      ensureTagIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tagIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 tagIds = 30;</code>
     *
     * <pre>
     * 相关标签清单
     * </pre>
     */
    public Builder clearTagIds() {
      tagIds_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00008000);
      onChanged();
      return this;
    }

    private java.util.List<Integer> topicIds_ = java.util.Collections.emptyList();
    private void ensureTopicIdsIsMutable() {
      if (!((bitField0_ & 0x00010000) == 0x00010000)) {
        topicIds_ = new java.util.ArrayList<Integer>(topicIds_);
        bitField0_ |= 0x00010000;
       }
    }
    /**
     * <code>repeated int32 topicIds = 31;</code>
     *
     * <pre>
     * 相关主题清单
     * </pre>
     */
    public java.util.List<Integer>
        getTopicIdsList() {
      return java.util.Collections.unmodifiableList(topicIds_);
    }
    /**
     * <code>repeated int32 topicIds = 31;</code>
     *
     * <pre>
     * 相关主题清单
     * </pre>
     */
    public int getTopicIdsCount() {
      return topicIds_.size();
    }
    /**
     * <code>repeated int32 topicIds = 31;</code>
     *
     * <pre>
     * 相关主题清单
     * </pre>
     */
    public int getTopicIds(int index) {
      return topicIds_.get(index);
    }
    /**
     * <code>repeated int32 topicIds = 31;</code>
     *
     * <pre>
     * 相关主题清单
     * </pre>
     */
    public Builder setTopicIds(
        int index, int value) {
      ensureTopicIdsIsMutable();
      topicIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 topicIds = 31;</code>
     *
     * <pre>
     * 相关主题清单
     * </pre>
     */
    public Builder addTopicIds(int value) {
      ensureTopicIdsIsMutable();
      topicIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 topicIds = 31;</code>
     *
     * <pre>
     * 相关主题清单
     * </pre>
     */
    public Builder addAllTopicIds(
        Iterable<? extends Integer> values) {
      ensureTopicIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, topicIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 topicIds = 31;</code>
     *
     * <pre>
     * 相关主题清单
     * </pre>
     */
    public Builder clearTopicIds() {
      topicIds_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00010000);
      onChanged();
      return this;
    }

    private java.util.List<Integer> relateIds_ = java.util.Collections.emptyList();
    private void ensureRelateIdsIsMutable() {
      if (!((bitField0_ & 0x00020000) == 0x00020000)) {
        relateIds_ = new java.util.ArrayList<Integer>(relateIds_);
        bitField0_ |= 0x00020000;
       }
    }
    /**
     * <code>repeated int32 relateIds = 32;</code>
     *
     * <pre>
     * 相关新闻清单
     * </pre>
     */
    public java.util.List<Integer>
        getRelateIdsList() {
      return java.util.Collections.unmodifiableList(relateIds_);
    }
    /**
     * <code>repeated int32 relateIds = 32;</code>
     *
     * <pre>
     * 相关新闻清单
     * </pre>
     */
    public int getRelateIdsCount() {
      return relateIds_.size();
    }
    /**
     * <code>repeated int32 relateIds = 32;</code>
     *
     * <pre>
     * 相关新闻清单
     * </pre>
     */
    public int getRelateIds(int index) {
      return relateIds_.get(index);
    }
    /**
     * <code>repeated int32 relateIds = 32;</code>
     *
     * <pre>
     * 相关新闻清单
     * </pre>
     */
    public Builder setRelateIds(
        int index, int value) {
      ensureRelateIdsIsMutable();
      relateIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 relateIds = 32;</code>
     *
     * <pre>
     * 相关新闻清单
     * </pre>
     */
    public Builder addRelateIds(int value) {
      ensureRelateIdsIsMutable();
      relateIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 relateIds = 32;</code>
     *
     * <pre>
     * 相关新闻清单
     * </pre>
     */
    public Builder addAllRelateIds(
        Iterable<? extends Integer> values) {
      ensureRelateIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, relateIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 relateIds = 32;</code>
     *
     * <pre>
     * 相关新闻清单
     * </pre>
     */
    public Builder clearRelateIds() {
      relateIds_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00020000);
      onChanged();
      return this;
    }

    private boolean rotate_ ;
    /**
     * <code>optional bool rotate = 40;</code>
     *
     * <pre>
     * 是否顶部轮播新闻   true:是，false：不是
     * </pre>
     */
    public boolean getRotate() {
      return rotate_;
    }
    /**
     * <code>optional bool rotate = 40;</code>
     *
     * <pre>
     * 是否顶部轮播新闻   true:是，false：不是
     * </pre>
     */
    public Builder setRotate(boolean value) {
      
      rotate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool rotate = 40;</code>
     *
     * <pre>
     * 是否顶部轮播新闻   true:是，false：不是
     * </pre>
     */
    public Builder clearRotate() {
      
      rotate_ = false;
      onChanged();
      return this;
    }

    private int cityId_ ;
    /**
     * <code>optional int32 cityId = 41;</code>
     *
     * <pre>
     * 所属城市ID
     * </pre>
     */
    public int getCityId() {
      return cityId_;
    }
    /**
     * <code>optional int32 cityId = 41;</code>
     *
     * <pre>
     * 所属城市ID
     * </pre>
     */
    public Builder setCityId(int value) {
      
      cityId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 cityId = 41;</code>
     *
     * <pre>
     * 所属城市ID
     * </pre>
     */
    public Builder clearCityId() {
      
      cityId_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.weiwuu.protobuf.News)
  }

  // @@protoc_insertion_point(class_scope:com.weiwuu.protobuf.News)
  private static final News DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new News();
  }

  public static News getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<News>
      PARSER = new com.google.protobuf.AbstractParser<News>() {
    public News parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new News(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<News> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<News> getParserForType() {
    return PARSER;
  }

  public News getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

