// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewsSubscribe.proto

package com.weiwuu.protobuf;

public interface NewsSubscribeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.weiwuu.protobuf.NewsSubscribe)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   *
   * <pre>
   * 订阅ID
   * </pre>
   */
  int getId();

  /**
   * <code>optional int32 userId = 2;</code>
   *
   * <pre>
   * 用户ID
   * </pre>
   */
  int getUserId();

  /**
   * <code>repeated int32 topicIds = 3;</code>
   *
   * <pre>
   * 订阅主题清单
   * </pre>
   */
  java.util.List<Integer> getTopicIdsList();
  /**
   * <code>repeated int32 topicIds = 3;</code>
   *
   * <pre>
   * 订阅主题清单
   * </pre>
   */
  int getTopicIdsCount();
  /**
   * <code>repeated int32 topicIds = 3;</code>
   *
   * <pre>
   * 订阅主题清单
   * </pre>
   */
  int getTopicIds(int index);
}
