// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewsFollow.proto

package com.weiwuu.protobuf;

public interface NewsFollowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.weiwuu.protobuf.NewsFollow)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   *
   * <pre>
   * 跟帖ID
   * </pre>
   */
  int getId();

  /**
   * <code>optional int32 newsId = 2;</code>
   *
   * <pre>
   * 消息ID
   * </pre>
   */
  int getNewsId();

  /**
   * <code>optional string issueTime = 3;</code>
   *
   * <pre>
   * 发布时间:  (yyyy-MM-dd hh:mm:dd)
   * </pre>
   */
  String getIssueTime();
  /**
   * <code>optional string issueTime = 3;</code>
   *
   * <pre>
   * 发布时间:  (yyyy-MM-dd hh:mm:dd)
   * </pre>
   */
  com.google.protobuf.ByteString
      getIssueTimeBytes();

  /**
   * <code>optional int32 authorId = 10;</code>
   *
   * <pre>
   * 作者 ID
   * </pre>
   */
  int getAuthorId();

  /**
   * <code>optional string authorNickName = 11;</code>
   *
   * <pre>
   * 作者的昵称
   * </pre>
   */
  String getAuthorNickName();
  /**
   * <code>optional string authorNickName = 11;</code>
   *
   * <pre>
   * 作者的昵称
   * </pre>
   */
  com.google.protobuf.ByteString
      getAuthorNickNameBytes();

  /**
   * <code>optional string authorAvatarURL = 12;</code>
   *
   * <pre>
   * 作者头像的URL
   * </pre>
   */
  String getAuthorAvatarURL();
  /**
   * <code>optional string authorAvatarURL = 12;</code>
   *
   * <pre>
   * 作者头像的URL
   * </pre>
   */
  com.google.protobuf.ByteString
      getAuthorAvatarURLBytes();

  /**
   * <code>optional string content = 15;</code>
   *
   * <pre>
   * 内容: (限制字数 &lt;= 2048)
   * </pre>
   */
  String getContent();
  /**
   * <code>optional string content = 15;</code>
   *
   * <pre>
   * 内容: (限制字数 &lt;= 2048)
   * </pre>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>optional int32 assentCount = 20;</code>
   *
   * <pre>
   * 赞同统计
   * </pre>
   */
  int getAssentCount();

  /**
   * <code>optional int32 opposeCount = 21;</code>
   *
   * <pre>
   * 反对统计
   * </pre>
   */
  int getOpposeCount();

  /**
   * <code>optional int32 reportCount = 22;</code>
   *
   * <pre>
   * 举报统计
   * </pre>
   */
  int getReportCount();
}
