// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewsList.proto

package com.weiwuu.protobuf;

/**
 * Protobuf type {@code com.weiwuu.protobuf.NewsList}
 *
 * <pre>
 * 消息
 * </pre>
 */
public  final class NewsList extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.weiwuu.protobuf.NewsList)
    NewsListOrBuilder {
  // Use NewsList.newBuilder() to construct.
  private NewsList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private NewsList() {
    newsTypeList_ = java.util.Collections.emptyList();
    newsTagList_ = java.util.Collections.emptyList();
    newsTopicList_ = java.util.Collections.emptyList();
    newsList_ = java.util.Collections.emptyList();
    newsFollowList_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private NewsList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              newsTypeList_ = new java.util.ArrayList<NewsType>();
              mutable_bitField0_ |= 0x00000001;
            }
            newsTypeList_.add(input.readMessage(NewsType.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              newsTagList_ = new java.util.ArrayList<NewsTag>();
              mutable_bitField0_ |= 0x00000002;
            }
            newsTagList_.add(input.readMessage(NewsTag.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              newsTopicList_ = new java.util.ArrayList<NewsTopic>();
              mutable_bitField0_ |= 0x00000004;
            }
            newsTopicList_.add(input.readMessage(NewsTopic.parser(), extensionRegistry));
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              newsList_ = new java.util.ArrayList<News>();
              mutable_bitField0_ |= 0x00000008;
            }
            newsList_.add(input.readMessage(News.parser(), extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              newsFollowList_ = new java.util.ArrayList<NewsFollow>();
              mutable_bitField0_ |= 0x00000010;
            }
            newsFollowList_.add(input.readMessage(NewsFollow.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        newsTypeList_ = java.util.Collections.unmodifiableList(newsTypeList_);
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        newsTagList_ = java.util.Collections.unmodifiableList(newsTagList_);
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        newsTopicList_ = java.util.Collections.unmodifiableList(newsTopicList_);
      }
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        newsList_ = java.util.Collections.unmodifiableList(newsList_);
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        newsFollowList_ = java.util.Collections.unmodifiableList(newsFollowList_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return NewsListProto.internal_static_com_weiwuu_protobuf_NewsList_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return NewsListProto.internal_static_com_weiwuu_protobuf_NewsList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            NewsList.class, Builder.class);
  }

  public static final int NEWSTYPELIST_FIELD_NUMBER = 1;
  private java.util.List<NewsType> newsTypeList_;
  /**
   * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
   *
   * <pre>
   * 分类列表
   * </pre>
   */
  public java.util.List<NewsType> getNewsTypeListList() {
    return newsTypeList_;
  }
  /**
   * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
   *
   * <pre>
   * 分类列表
   * </pre>
   */
  public java.util.List<? extends NewsTypeOrBuilder>
      getNewsTypeListOrBuilderList() {
    return newsTypeList_;
  }
  /**
   * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
   *
   * <pre>
   * 分类列表
   * </pre>
   */
  public int getNewsTypeListCount() {
    return newsTypeList_.size();
  }
  /**
   * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
   *
   * <pre>
   * 分类列表
   * </pre>
   */
  public NewsType getNewsTypeList(int index) {
    return newsTypeList_.get(index);
  }
  /**
   * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
   *
   * <pre>
   * 分类列表
   * </pre>
   */
  public NewsTypeOrBuilder getNewsTypeListOrBuilder(
      int index) {
    return newsTypeList_.get(index);
  }

  public static final int NEWSTAGLIST_FIELD_NUMBER = 2;
  private java.util.List<NewsTag> newsTagList_;
  /**
   * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
   *
   * <pre>
   * 标签列表
   * </pre>
   */
  public java.util.List<NewsTag> getNewsTagListList() {
    return newsTagList_;
  }
  /**
   * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
   *
   * <pre>
   * 标签列表
   * </pre>
   */
  public java.util.List<? extends NewsTagOrBuilder>
      getNewsTagListOrBuilderList() {
    return newsTagList_;
  }
  /**
   * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
   *
   * <pre>
   * 标签列表
   * </pre>
   */
  public int getNewsTagListCount() {
    return newsTagList_.size();
  }
  /**
   * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
   *
   * <pre>
   * 标签列表
   * </pre>
   */
  public NewsTag getNewsTagList(int index) {
    return newsTagList_.get(index);
  }
  /**
   * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
   *
   * <pre>
   * 标签列表
   * </pre>
   */
  public NewsTagOrBuilder getNewsTagListOrBuilder(
      int index) {
    return newsTagList_.get(index);
  }

  public static final int NEWSTOPICLIST_FIELD_NUMBER = 3;
  private java.util.List<NewsTopic> newsTopicList_;
  /**
   * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
   *
   * <pre>
   * 主题列表
   * </pre>
   */
  public java.util.List<NewsTopic> getNewsTopicListList() {
    return newsTopicList_;
  }
  /**
   * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
   *
   * <pre>
   * 主题列表
   * </pre>
   */
  public java.util.List<? extends NewsTopicOrBuilder>
      getNewsTopicListOrBuilderList() {
    return newsTopicList_;
  }
  /**
   * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
   *
   * <pre>
   * 主题列表
   * </pre>
   */
  public int getNewsTopicListCount() {
    return newsTopicList_.size();
  }
  /**
   * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
   *
   * <pre>
   * 主题列表
   * </pre>
   */
  public NewsTopic getNewsTopicList(int index) {
    return newsTopicList_.get(index);
  }
  /**
   * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
   *
   * <pre>
   * 主题列表
   * </pre>
   */
  public NewsTopicOrBuilder getNewsTopicListOrBuilder(
      int index) {
    return newsTopicList_.get(index);
  }

  public static final int NEWSLIST_FIELD_NUMBER = 4;
  private java.util.List<News> newsList_;
  /**
   * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
   *
   * <pre>
   * 资讯列表
   * </pre>
   */
  public java.util.List<News> getNewsListList() {
    return newsList_;
  }
  /**
   * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
   *
   * <pre>
   * 资讯列表
   * </pre>
   */
  public java.util.List<? extends NewsOrBuilder>
      getNewsListOrBuilderList() {
    return newsList_;
  }
  /**
   * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
   *
   * <pre>
   * 资讯列表
   * </pre>
   */
  public int getNewsListCount() {
    return newsList_.size();
  }
  /**
   * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
   *
   * <pre>
   * 资讯列表
   * </pre>
   */
  public News getNewsList(int index) {
    return newsList_.get(index);
  }
  /**
   * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
   *
   * <pre>
   * 资讯列表
   * </pre>
   */
  public NewsOrBuilder getNewsListOrBuilder(
      int index) {
    return newsList_.get(index);
  }

  public static final int NEWSFOLLOWLIST_FIELD_NUMBER = 5;
  private java.util.List<NewsFollow> newsFollowList_;
  /**
   * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
   *
   * <pre>
   * 评论列表
   * </pre>
   */
  public java.util.List<NewsFollow> getNewsFollowListList() {
    return newsFollowList_;
  }
  /**
   * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
   *
   * <pre>
   * 评论列表
   * </pre>
   */
  public java.util.List<? extends NewsFollowOrBuilder>
      getNewsFollowListOrBuilderList() {
    return newsFollowList_;
  }
  /**
   * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
   *
   * <pre>
   * 评论列表
   * </pre>
   */
  public int getNewsFollowListCount() {
    return newsFollowList_.size();
  }
  /**
   * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
   *
   * <pre>
   * 评论列表
   * </pre>
   */
  public NewsFollow getNewsFollowList(int index) {
    return newsFollowList_.get(index);
  }
  /**
   * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
   *
   * <pre>
   * 评论列表
   * </pre>
   */
  public NewsFollowOrBuilder getNewsFollowListOrBuilder(
      int index) {
    return newsFollowList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < newsTypeList_.size(); i++) {
      output.writeMessage(1, newsTypeList_.get(i));
    }
    for (int i = 0; i < newsTagList_.size(); i++) {
      output.writeMessage(2, newsTagList_.get(i));
    }
    for (int i = 0; i < newsTopicList_.size(); i++) {
      output.writeMessage(3, newsTopicList_.get(i));
    }
    for (int i = 0; i < newsList_.size(); i++) {
      output.writeMessage(4, newsList_.get(i));
    }
    for (int i = 0; i < newsFollowList_.size(); i++) {
      output.writeMessage(5, newsFollowList_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < newsTypeList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, newsTypeList_.get(i));
    }
    for (int i = 0; i < newsTagList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, newsTagList_.get(i));
    }
    for (int i = 0; i < newsTopicList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, newsTopicList_.get(i));
    }
    for (int i = 0; i < newsList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, newsList_.get(i));
    }
    for (int i = 0; i < newsFollowList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, newsFollowList_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof NewsList)) {
      return super.equals(obj);
    }
    NewsList other = (NewsList) obj;

    boolean result = true;
    result = result && getNewsTypeListList()
        .equals(other.getNewsTypeListList());
    result = result && getNewsTagListList()
        .equals(other.getNewsTagListList());
    result = result && getNewsTopicListList()
        .equals(other.getNewsTopicListList());
    result = result && getNewsListList()
        .equals(other.getNewsListList());
    result = result && getNewsFollowListList()
        .equals(other.getNewsFollowListList());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getNewsTypeListCount() > 0) {
      hash = (37 * hash) + NEWSTYPELIST_FIELD_NUMBER;
      hash = (53 * hash) + getNewsTypeListList().hashCode();
    }
    if (getNewsTagListCount() > 0) {
      hash = (37 * hash) + NEWSTAGLIST_FIELD_NUMBER;
      hash = (53 * hash) + getNewsTagListList().hashCode();
    }
    if (getNewsTopicListCount() > 0) {
      hash = (37 * hash) + NEWSTOPICLIST_FIELD_NUMBER;
      hash = (53 * hash) + getNewsTopicListList().hashCode();
    }
    if (getNewsListCount() > 0) {
      hash = (37 * hash) + NEWSLIST_FIELD_NUMBER;
      hash = (53 * hash) + getNewsListList().hashCode();
    }
    if (getNewsFollowListCount() > 0) {
      hash = (37 * hash) + NEWSFOLLOWLIST_FIELD_NUMBER;
      hash = (53 * hash) + getNewsFollowListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static NewsList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NewsList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NewsList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NewsList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NewsList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static NewsList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static NewsList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static NewsList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static NewsList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static NewsList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(NewsList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.weiwuu.protobuf.NewsList}
   *
   * <pre>
   * 消息
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.weiwuu.protobuf.NewsList)
      NewsListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NewsListProto.internal_static_com_weiwuu_protobuf_NewsList_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NewsListProto.internal_static_com_weiwuu_protobuf_NewsList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NewsList.class, Builder.class);
    }

    // Construct using com.weiwuu.protobuf.NewsList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getNewsTypeListFieldBuilder();
        getNewsTagListFieldBuilder();
        getNewsTopicListFieldBuilder();
        getNewsListFieldBuilder();
        getNewsFollowListFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (newsTypeListBuilder_ == null) {
        newsTypeList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        newsTypeListBuilder_.clear();
      }
      if (newsTagListBuilder_ == null) {
        newsTagList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        newsTagListBuilder_.clear();
      }
      if (newsTopicListBuilder_ == null) {
        newsTopicList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        newsTopicListBuilder_.clear();
      }
      if (newsListBuilder_ == null) {
        newsList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        newsListBuilder_.clear();
      }
      if (newsFollowListBuilder_ == null) {
        newsFollowList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        newsFollowListBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return NewsListProto.internal_static_com_weiwuu_protobuf_NewsList_descriptor;
    }

    public NewsList getDefaultInstanceForType() {
      return NewsList.getDefaultInstance();
    }

    public NewsList build() {
      NewsList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public NewsList buildPartial() {
      NewsList result = new NewsList(this);
      int from_bitField0_ = bitField0_;
      if (newsTypeListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          newsTypeList_ = java.util.Collections.unmodifiableList(newsTypeList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.newsTypeList_ = newsTypeList_;
      } else {
        result.newsTypeList_ = newsTypeListBuilder_.build();
      }
      if (newsTagListBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          newsTagList_ = java.util.Collections.unmodifiableList(newsTagList_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.newsTagList_ = newsTagList_;
      } else {
        result.newsTagList_ = newsTagListBuilder_.build();
      }
      if (newsTopicListBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          newsTopicList_ = java.util.Collections.unmodifiableList(newsTopicList_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.newsTopicList_ = newsTopicList_;
      } else {
        result.newsTopicList_ = newsTopicListBuilder_.build();
      }
      if (newsListBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          newsList_ = java.util.Collections.unmodifiableList(newsList_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.newsList_ = newsList_;
      } else {
        result.newsList_ = newsListBuilder_.build();
      }
      if (newsFollowListBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          newsFollowList_ = java.util.Collections.unmodifiableList(newsFollowList_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.newsFollowList_ = newsFollowList_;
      } else {
        result.newsFollowList_ = newsFollowListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof NewsList) {
        return mergeFrom((NewsList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(NewsList other) {
      if (other == NewsList.getDefaultInstance()) return this;
      if (newsTypeListBuilder_ == null) {
        if (!other.newsTypeList_.isEmpty()) {
          if (newsTypeList_.isEmpty()) {
            newsTypeList_ = other.newsTypeList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNewsTypeListIsMutable();
            newsTypeList_.addAll(other.newsTypeList_);
          }
          onChanged();
        }
      } else {
        if (!other.newsTypeList_.isEmpty()) {
          if (newsTypeListBuilder_.isEmpty()) {
            newsTypeListBuilder_.dispose();
            newsTypeListBuilder_ = null;
            newsTypeList_ = other.newsTypeList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            newsTypeListBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getNewsTypeListFieldBuilder() : null;
          } else {
            newsTypeListBuilder_.addAllMessages(other.newsTypeList_);
          }
        }
      }
      if (newsTagListBuilder_ == null) {
        if (!other.newsTagList_.isEmpty()) {
          if (newsTagList_.isEmpty()) {
            newsTagList_ = other.newsTagList_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureNewsTagListIsMutable();
            newsTagList_.addAll(other.newsTagList_);
          }
          onChanged();
        }
      } else {
        if (!other.newsTagList_.isEmpty()) {
          if (newsTagListBuilder_.isEmpty()) {
            newsTagListBuilder_.dispose();
            newsTagListBuilder_ = null;
            newsTagList_ = other.newsTagList_;
            bitField0_ = (bitField0_ & ~0x00000002);
            newsTagListBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getNewsTagListFieldBuilder() : null;
          } else {
            newsTagListBuilder_.addAllMessages(other.newsTagList_);
          }
        }
      }
      if (newsTopicListBuilder_ == null) {
        if (!other.newsTopicList_.isEmpty()) {
          if (newsTopicList_.isEmpty()) {
            newsTopicList_ = other.newsTopicList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureNewsTopicListIsMutable();
            newsTopicList_.addAll(other.newsTopicList_);
          }
          onChanged();
        }
      } else {
        if (!other.newsTopicList_.isEmpty()) {
          if (newsTopicListBuilder_.isEmpty()) {
            newsTopicListBuilder_.dispose();
            newsTopicListBuilder_ = null;
            newsTopicList_ = other.newsTopicList_;
            bitField0_ = (bitField0_ & ~0x00000004);
            newsTopicListBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getNewsTopicListFieldBuilder() : null;
          } else {
            newsTopicListBuilder_.addAllMessages(other.newsTopicList_);
          }
        }
      }
      if (newsListBuilder_ == null) {
        if (!other.newsList_.isEmpty()) {
          if (newsList_.isEmpty()) {
            newsList_ = other.newsList_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureNewsListIsMutable();
            newsList_.addAll(other.newsList_);
          }
          onChanged();
        }
      } else {
        if (!other.newsList_.isEmpty()) {
          if (newsListBuilder_.isEmpty()) {
            newsListBuilder_.dispose();
            newsListBuilder_ = null;
            newsList_ = other.newsList_;
            bitField0_ = (bitField0_ & ~0x00000008);
            newsListBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getNewsListFieldBuilder() : null;
          } else {
            newsListBuilder_.addAllMessages(other.newsList_);
          }
        }
      }
      if (newsFollowListBuilder_ == null) {
        if (!other.newsFollowList_.isEmpty()) {
          if (newsFollowList_.isEmpty()) {
            newsFollowList_ = other.newsFollowList_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureNewsFollowListIsMutable();
            newsFollowList_.addAll(other.newsFollowList_);
          }
          onChanged();
        }
      } else {
        if (!other.newsFollowList_.isEmpty()) {
          if (newsFollowListBuilder_.isEmpty()) {
            newsFollowListBuilder_.dispose();
            newsFollowListBuilder_ = null;
            newsFollowList_ = other.newsFollowList_;
            bitField0_ = (bitField0_ & ~0x00000010);
            newsFollowListBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getNewsFollowListFieldBuilder() : null;
          } else {
            newsFollowListBuilder_.addAllMessages(other.newsFollowList_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      NewsList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (NewsList) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<NewsType> newsTypeList_ =
      java.util.Collections.emptyList();
    private void ensureNewsTypeListIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        newsTypeList_ = new java.util.ArrayList<NewsType>(newsTypeList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        NewsType, NewsType.Builder, NewsTypeOrBuilder> newsTypeListBuilder_;

    /**
     * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
     *
     * <pre>
     * 分类列表
     * </pre>
     */
    public java.util.List<NewsType> getNewsTypeListList() {
      if (newsTypeListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(newsTypeList_);
      } else {
        return newsTypeListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
     *
     * <pre>
     * 分类列表
     * </pre>
     */
    public int getNewsTypeListCount() {
      if (newsTypeListBuilder_ == null) {
        return newsTypeList_.size();
      } else {
        return newsTypeListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
     *
     * <pre>
     * 分类列表
     * </pre>
     */
    public NewsType getNewsTypeList(int index) {
      if (newsTypeListBuilder_ == null) {
        return newsTypeList_.get(index);
      } else {
        return newsTypeListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
     *
     * <pre>
     * 分类列表
     * </pre>
     */
    public Builder setNewsTypeList(
        int index, NewsType value) {
      if (newsTypeListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewsTypeListIsMutable();
        newsTypeList_.set(index, value);
        onChanged();
      } else {
        newsTypeListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
     *
     * <pre>
     * 分类列表
     * </pre>
     */
    public Builder setNewsTypeList(
        int index, NewsType.Builder builderForValue) {
      if (newsTypeListBuilder_ == null) {
        ensureNewsTypeListIsMutable();
        newsTypeList_.set(index, builderForValue.build());
        onChanged();
      } else {
        newsTypeListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
     *
     * <pre>
     * 分类列表
     * </pre>
     */
    public Builder addNewsTypeList(NewsType value) {
      if (newsTypeListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewsTypeListIsMutable();
        newsTypeList_.add(value);
        onChanged();
      } else {
        newsTypeListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
     *
     * <pre>
     * 分类列表
     * </pre>
     */
    public Builder addNewsTypeList(
        int index, NewsType value) {
      if (newsTypeListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewsTypeListIsMutable();
        newsTypeList_.add(index, value);
        onChanged();
      } else {
        newsTypeListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
     *
     * <pre>
     * 分类列表
     * </pre>
     */
    public Builder addNewsTypeList(
        NewsType.Builder builderForValue) {
      if (newsTypeListBuilder_ == null) {
        ensureNewsTypeListIsMutable();
        newsTypeList_.add(builderForValue.build());
        onChanged();
      } else {
        newsTypeListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
     *
     * <pre>
     * 分类列表
     * </pre>
     */
    public Builder addNewsTypeList(
        int index, NewsType.Builder builderForValue) {
      if (newsTypeListBuilder_ == null) {
        ensureNewsTypeListIsMutable();
        newsTypeList_.add(index, builderForValue.build());
        onChanged();
      } else {
        newsTypeListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
     *
     * <pre>
     * 分类列表
     * </pre>
     */
    public Builder addAllNewsTypeList(
        Iterable<? extends NewsType> values) {
      if (newsTypeListBuilder_ == null) {
        ensureNewsTypeListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, newsTypeList_);
        onChanged();
      } else {
        newsTypeListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
     *
     * <pre>
     * 分类列表
     * </pre>
     */
    public Builder clearNewsTypeList() {
      if (newsTypeListBuilder_ == null) {
        newsTypeList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        newsTypeListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
     *
     * <pre>
     * 分类列表
     * </pre>
     */
    public Builder removeNewsTypeList(int index) {
      if (newsTypeListBuilder_ == null) {
        ensureNewsTypeListIsMutable();
        newsTypeList_.remove(index);
        onChanged();
      } else {
        newsTypeListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
     *
     * <pre>
     * 分类列表
     * </pre>
     */
    public NewsType.Builder getNewsTypeListBuilder(
        int index) {
      return getNewsTypeListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
     *
     * <pre>
     * 分类列表
     * </pre>
     */
    public NewsTypeOrBuilder getNewsTypeListOrBuilder(
        int index) {
      if (newsTypeListBuilder_ == null) {
        return newsTypeList_.get(index);  } else {
        return newsTypeListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
     *
     * <pre>
     * 分类列表
     * </pre>
     */
    public java.util.List<? extends NewsTypeOrBuilder>
         getNewsTypeListOrBuilderList() {
      if (newsTypeListBuilder_ != null) {
        return newsTypeListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(newsTypeList_);
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
     *
     * <pre>
     * 分类列表
     * </pre>
     */
    public NewsType.Builder addNewsTypeListBuilder() {
      return getNewsTypeListFieldBuilder().addBuilder(
          NewsType.getDefaultInstance());
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
     *
     * <pre>
     * 分类列表
     * </pre>
     */
    public NewsType.Builder addNewsTypeListBuilder(
        int index) {
      return getNewsTypeListFieldBuilder().addBuilder(
          index, NewsType.getDefaultInstance());
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsType newsTypeList = 1;</code>
     *
     * <pre>
     * 分类列表
     * </pre>
     */
    public java.util.List<NewsType.Builder>
         getNewsTypeListBuilderList() {
      return getNewsTypeListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        NewsType, NewsType.Builder, NewsTypeOrBuilder>
        getNewsTypeListFieldBuilder() {
      if (newsTypeListBuilder_ == null) {
        newsTypeListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            NewsType, NewsType.Builder, NewsTypeOrBuilder>(
                newsTypeList_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        newsTypeList_ = null;
      }
      return newsTypeListBuilder_;
    }

    private java.util.List<NewsTag> newsTagList_ =
      java.util.Collections.emptyList();
    private void ensureNewsTagListIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        newsTagList_ = new java.util.ArrayList<NewsTag>(newsTagList_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        NewsTag, NewsTag.Builder, NewsTagOrBuilder> newsTagListBuilder_;

    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
     *
     * <pre>
     * 标签列表
     * </pre>
     */
    public java.util.List<NewsTag> getNewsTagListList() {
      if (newsTagListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(newsTagList_);
      } else {
        return newsTagListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
     *
     * <pre>
     * 标签列表
     * </pre>
     */
    public int getNewsTagListCount() {
      if (newsTagListBuilder_ == null) {
        return newsTagList_.size();
      } else {
        return newsTagListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
     *
     * <pre>
     * 标签列表
     * </pre>
     */
    public NewsTag getNewsTagList(int index) {
      if (newsTagListBuilder_ == null) {
        return newsTagList_.get(index);
      } else {
        return newsTagListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
     *
     * <pre>
     * 标签列表
     * </pre>
     */
    public Builder setNewsTagList(
        int index, NewsTag value) {
      if (newsTagListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewsTagListIsMutable();
        newsTagList_.set(index, value);
        onChanged();
      } else {
        newsTagListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
     *
     * <pre>
     * 标签列表
     * </pre>
     */
    public Builder setNewsTagList(
        int index, NewsTag.Builder builderForValue) {
      if (newsTagListBuilder_ == null) {
        ensureNewsTagListIsMutable();
        newsTagList_.set(index, builderForValue.build());
        onChanged();
      } else {
        newsTagListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
     *
     * <pre>
     * 标签列表
     * </pre>
     */
    public Builder addNewsTagList(NewsTag value) {
      if (newsTagListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewsTagListIsMutable();
        newsTagList_.add(value);
        onChanged();
      } else {
        newsTagListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
     *
     * <pre>
     * 标签列表
     * </pre>
     */
    public Builder addNewsTagList(
        int index, NewsTag value) {
      if (newsTagListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewsTagListIsMutable();
        newsTagList_.add(index, value);
        onChanged();
      } else {
        newsTagListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
     *
     * <pre>
     * 标签列表
     * </pre>
     */
    public Builder addNewsTagList(
        NewsTag.Builder builderForValue) {
      if (newsTagListBuilder_ == null) {
        ensureNewsTagListIsMutable();
        newsTagList_.add(builderForValue.build());
        onChanged();
      } else {
        newsTagListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
     *
     * <pre>
     * 标签列表
     * </pre>
     */
    public Builder addNewsTagList(
        int index, NewsTag.Builder builderForValue) {
      if (newsTagListBuilder_ == null) {
        ensureNewsTagListIsMutable();
        newsTagList_.add(index, builderForValue.build());
        onChanged();
      } else {
        newsTagListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
     *
     * <pre>
     * 标签列表
     * </pre>
     */
    public Builder addAllNewsTagList(
        Iterable<? extends NewsTag> values) {
      if (newsTagListBuilder_ == null) {
        ensureNewsTagListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, newsTagList_);
        onChanged();
      } else {
        newsTagListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
     *
     * <pre>
     * 标签列表
     * </pre>
     */
    public Builder clearNewsTagList() {
      if (newsTagListBuilder_ == null) {
        newsTagList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        newsTagListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
     *
     * <pre>
     * 标签列表
     * </pre>
     */
    public Builder removeNewsTagList(int index) {
      if (newsTagListBuilder_ == null) {
        ensureNewsTagListIsMutable();
        newsTagList_.remove(index);
        onChanged();
      } else {
        newsTagListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
     *
     * <pre>
     * 标签列表
     * </pre>
     */
    public NewsTag.Builder getNewsTagListBuilder(
        int index) {
      return getNewsTagListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
     *
     * <pre>
     * 标签列表
     * </pre>
     */
    public NewsTagOrBuilder getNewsTagListOrBuilder(
        int index) {
      if (newsTagListBuilder_ == null) {
        return newsTagList_.get(index);  } else {
        return newsTagListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
     *
     * <pre>
     * 标签列表
     * </pre>
     */
    public java.util.List<? extends NewsTagOrBuilder>
         getNewsTagListOrBuilderList() {
      if (newsTagListBuilder_ != null) {
        return newsTagListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(newsTagList_);
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
     *
     * <pre>
     * 标签列表
     * </pre>
     */
    public NewsTag.Builder addNewsTagListBuilder() {
      return getNewsTagListFieldBuilder().addBuilder(
          NewsTag.getDefaultInstance());
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
     *
     * <pre>
     * 标签列表
     * </pre>
     */
    public NewsTag.Builder addNewsTagListBuilder(
        int index) {
      return getNewsTagListFieldBuilder().addBuilder(
          index, NewsTag.getDefaultInstance());
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTag newsTagList = 2;</code>
     *
     * <pre>
     * 标签列表
     * </pre>
     */
    public java.util.List<NewsTag.Builder>
         getNewsTagListBuilderList() {
      return getNewsTagListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        NewsTag, NewsTag.Builder, NewsTagOrBuilder>
        getNewsTagListFieldBuilder() {
      if (newsTagListBuilder_ == null) {
        newsTagListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            NewsTag, NewsTag.Builder, NewsTagOrBuilder>(
                newsTagList_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        newsTagList_ = null;
      }
      return newsTagListBuilder_;
    }

    private java.util.List<NewsTopic> newsTopicList_ =
      java.util.Collections.emptyList();
    private void ensureNewsTopicListIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        newsTopicList_ = new java.util.ArrayList<NewsTopic>(newsTopicList_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        NewsTopic, NewsTopic.Builder, NewsTopicOrBuilder> newsTopicListBuilder_;

    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
     *
     * <pre>
     * 主题列表
     * </pre>
     */
    public java.util.List<NewsTopic> getNewsTopicListList() {
      if (newsTopicListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(newsTopicList_);
      } else {
        return newsTopicListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
     *
     * <pre>
     * 主题列表
     * </pre>
     */
    public int getNewsTopicListCount() {
      if (newsTopicListBuilder_ == null) {
        return newsTopicList_.size();
      } else {
        return newsTopicListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
     *
     * <pre>
     * 主题列表
     * </pre>
     */
    public NewsTopic getNewsTopicList(int index) {
      if (newsTopicListBuilder_ == null) {
        return newsTopicList_.get(index);
      } else {
        return newsTopicListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
     *
     * <pre>
     * 主题列表
     * </pre>
     */
    public Builder setNewsTopicList(
        int index, NewsTopic value) {
      if (newsTopicListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewsTopicListIsMutable();
        newsTopicList_.set(index, value);
        onChanged();
      } else {
        newsTopicListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
     *
     * <pre>
     * 主题列表
     * </pre>
     */
    public Builder setNewsTopicList(
        int index, NewsTopic.Builder builderForValue) {
      if (newsTopicListBuilder_ == null) {
        ensureNewsTopicListIsMutable();
        newsTopicList_.set(index, builderForValue.build());
        onChanged();
      } else {
        newsTopicListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
     *
     * <pre>
     * 主题列表
     * </pre>
     */
    public Builder addNewsTopicList(NewsTopic value) {
      if (newsTopicListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewsTopicListIsMutable();
        newsTopicList_.add(value);
        onChanged();
      } else {
        newsTopicListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
     *
     * <pre>
     * 主题列表
     * </pre>
     */
    public Builder addNewsTopicList(
        int index, NewsTopic value) {
      if (newsTopicListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewsTopicListIsMutable();
        newsTopicList_.add(index, value);
        onChanged();
      } else {
        newsTopicListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
     *
     * <pre>
     * 主题列表
     * </pre>
     */
    public Builder addNewsTopicList(
        NewsTopic.Builder builderForValue) {
      if (newsTopicListBuilder_ == null) {
        ensureNewsTopicListIsMutable();
        newsTopicList_.add(builderForValue.build());
        onChanged();
      } else {
        newsTopicListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
     *
     * <pre>
     * 主题列表
     * </pre>
     */
    public Builder addNewsTopicList(
        int index, NewsTopic.Builder builderForValue) {
      if (newsTopicListBuilder_ == null) {
        ensureNewsTopicListIsMutable();
        newsTopicList_.add(index, builderForValue.build());
        onChanged();
      } else {
        newsTopicListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
     *
     * <pre>
     * 主题列表
     * </pre>
     */
    public Builder addAllNewsTopicList(
        Iterable<? extends NewsTopic> values) {
      if (newsTopicListBuilder_ == null) {
        ensureNewsTopicListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, newsTopicList_);
        onChanged();
      } else {
        newsTopicListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
     *
     * <pre>
     * 主题列表
     * </pre>
     */
    public Builder clearNewsTopicList() {
      if (newsTopicListBuilder_ == null) {
        newsTopicList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        newsTopicListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
     *
     * <pre>
     * 主题列表
     * </pre>
     */
    public Builder removeNewsTopicList(int index) {
      if (newsTopicListBuilder_ == null) {
        ensureNewsTopicListIsMutable();
        newsTopicList_.remove(index);
        onChanged();
      } else {
        newsTopicListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
     *
     * <pre>
     * 主题列表
     * </pre>
     */
    public NewsTopic.Builder getNewsTopicListBuilder(
        int index) {
      return getNewsTopicListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
     *
     * <pre>
     * 主题列表
     * </pre>
     */
    public NewsTopicOrBuilder getNewsTopicListOrBuilder(
        int index) {
      if (newsTopicListBuilder_ == null) {
        return newsTopicList_.get(index);  } else {
        return newsTopicListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
     *
     * <pre>
     * 主题列表
     * </pre>
     */
    public java.util.List<? extends NewsTopicOrBuilder>
         getNewsTopicListOrBuilderList() {
      if (newsTopicListBuilder_ != null) {
        return newsTopicListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(newsTopicList_);
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
     *
     * <pre>
     * 主题列表
     * </pre>
     */
    public NewsTopic.Builder addNewsTopicListBuilder() {
      return getNewsTopicListFieldBuilder().addBuilder(
          NewsTopic.getDefaultInstance());
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
     *
     * <pre>
     * 主题列表
     * </pre>
     */
    public NewsTopic.Builder addNewsTopicListBuilder(
        int index) {
      return getNewsTopicListFieldBuilder().addBuilder(
          index, NewsTopic.getDefaultInstance());
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsTopic newsTopicList = 3;</code>
     *
     * <pre>
     * 主题列表
     * </pre>
     */
    public java.util.List<NewsTopic.Builder>
         getNewsTopicListBuilderList() {
      return getNewsTopicListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        NewsTopic, NewsTopic.Builder, NewsTopicOrBuilder>
        getNewsTopicListFieldBuilder() {
      if (newsTopicListBuilder_ == null) {
        newsTopicListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            NewsTopic, NewsTopic.Builder, NewsTopicOrBuilder>(
                newsTopicList_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        newsTopicList_ = null;
      }
      return newsTopicListBuilder_;
    }

    private java.util.List<News> newsList_ =
      java.util.Collections.emptyList();
    private void ensureNewsListIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        newsList_ = new java.util.ArrayList<News>(newsList_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        News, News.Builder, NewsOrBuilder> newsListBuilder_;

    /**
     * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
     *
     * <pre>
     * 资讯列表
     * </pre>
     */
    public java.util.List<News> getNewsListList() {
      if (newsListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(newsList_);
      } else {
        return newsListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
     *
     * <pre>
     * 资讯列表
     * </pre>
     */
    public int getNewsListCount() {
      if (newsListBuilder_ == null) {
        return newsList_.size();
      } else {
        return newsListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
     *
     * <pre>
     * 资讯列表
     * </pre>
     */
    public News getNewsList(int index) {
      if (newsListBuilder_ == null) {
        return newsList_.get(index);
      } else {
        return newsListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
     *
     * <pre>
     * 资讯列表
     * </pre>
     */
    public Builder setNewsList(
        int index, News value) {
      if (newsListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewsListIsMutable();
        newsList_.set(index, value);
        onChanged();
      } else {
        newsListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
     *
     * <pre>
     * 资讯列表
     * </pre>
     */
    public Builder setNewsList(
        int index, News.Builder builderForValue) {
      if (newsListBuilder_ == null) {
        ensureNewsListIsMutable();
        newsList_.set(index, builderForValue.build());
        onChanged();
      } else {
        newsListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
     *
     * <pre>
     * 资讯列表
     * </pre>
     */
    public Builder addNewsList(News value) {
      if (newsListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewsListIsMutable();
        newsList_.add(value);
        onChanged();
      } else {
        newsListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
     *
     * <pre>
     * 资讯列表
     * </pre>
     */
    public Builder addNewsList(
        int index, News value) {
      if (newsListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewsListIsMutable();
        newsList_.add(index, value);
        onChanged();
      } else {
        newsListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
     *
     * <pre>
     * 资讯列表
     * </pre>
     */
    public Builder addNewsList(
        News.Builder builderForValue) {
      if (newsListBuilder_ == null) {
        ensureNewsListIsMutable();
        newsList_.add(builderForValue.build());
        onChanged();
      } else {
        newsListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
     *
     * <pre>
     * 资讯列表
     * </pre>
     */
    public Builder addNewsList(
        int index, News.Builder builderForValue) {
      if (newsListBuilder_ == null) {
        ensureNewsListIsMutable();
        newsList_.add(index, builderForValue.build());
        onChanged();
      } else {
        newsListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
     *
     * <pre>
     * 资讯列表
     * </pre>
     */
    public Builder addAllNewsList(
        Iterable<? extends News> values) {
      if (newsListBuilder_ == null) {
        ensureNewsListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, newsList_);
        onChanged();
      } else {
        newsListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
     *
     * <pre>
     * 资讯列表
     * </pre>
     */
    public Builder clearNewsList() {
      if (newsListBuilder_ == null) {
        newsList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        newsListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
     *
     * <pre>
     * 资讯列表
     * </pre>
     */
    public Builder removeNewsList(int index) {
      if (newsListBuilder_ == null) {
        ensureNewsListIsMutable();
        newsList_.remove(index);
        onChanged();
      } else {
        newsListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
     *
     * <pre>
     * 资讯列表
     * </pre>
     */
    public News.Builder getNewsListBuilder(
        int index) {
      return getNewsListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
     *
     * <pre>
     * 资讯列表
     * </pre>
     */
    public NewsOrBuilder getNewsListOrBuilder(
        int index) {
      if (newsListBuilder_ == null) {
        return newsList_.get(index);  } else {
        return newsListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
     *
     * <pre>
     * 资讯列表
     * </pre>
     */
    public java.util.List<? extends NewsOrBuilder>
         getNewsListOrBuilderList() {
      if (newsListBuilder_ != null) {
        return newsListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(newsList_);
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
     *
     * <pre>
     * 资讯列表
     * </pre>
     */
    public News.Builder addNewsListBuilder() {
      return getNewsListFieldBuilder().addBuilder(
          News.getDefaultInstance());
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
     *
     * <pre>
     * 资讯列表
     * </pre>
     */
    public News.Builder addNewsListBuilder(
        int index) {
      return getNewsListFieldBuilder().addBuilder(
          index, News.getDefaultInstance());
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.News newsList = 4;</code>
     *
     * <pre>
     * 资讯列表
     * </pre>
     */
    public java.util.List<News.Builder>
         getNewsListBuilderList() {
      return getNewsListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        News, News.Builder, NewsOrBuilder>
        getNewsListFieldBuilder() {
      if (newsListBuilder_ == null) {
        newsListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            News, News.Builder, NewsOrBuilder>(
                newsList_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        newsList_ = null;
      }
      return newsListBuilder_;
    }

    private java.util.List<NewsFollow> newsFollowList_ =
      java.util.Collections.emptyList();
    private void ensureNewsFollowListIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        newsFollowList_ = new java.util.ArrayList<NewsFollow>(newsFollowList_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        NewsFollow, NewsFollow.Builder, NewsFollowOrBuilder> newsFollowListBuilder_;

    /**
     * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
     *
     * <pre>
     * 评论列表
     * </pre>
     */
    public java.util.List<NewsFollow> getNewsFollowListList() {
      if (newsFollowListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(newsFollowList_);
      } else {
        return newsFollowListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
     *
     * <pre>
     * 评论列表
     * </pre>
     */
    public int getNewsFollowListCount() {
      if (newsFollowListBuilder_ == null) {
        return newsFollowList_.size();
      } else {
        return newsFollowListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
     *
     * <pre>
     * 评论列表
     * </pre>
     */
    public NewsFollow getNewsFollowList(int index) {
      if (newsFollowListBuilder_ == null) {
        return newsFollowList_.get(index);
      } else {
        return newsFollowListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
     *
     * <pre>
     * 评论列表
     * </pre>
     */
    public Builder setNewsFollowList(
        int index, NewsFollow value) {
      if (newsFollowListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewsFollowListIsMutable();
        newsFollowList_.set(index, value);
        onChanged();
      } else {
        newsFollowListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
     *
     * <pre>
     * 评论列表
     * </pre>
     */
    public Builder setNewsFollowList(
        int index, NewsFollow.Builder builderForValue) {
      if (newsFollowListBuilder_ == null) {
        ensureNewsFollowListIsMutable();
        newsFollowList_.set(index, builderForValue.build());
        onChanged();
      } else {
        newsFollowListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
     *
     * <pre>
     * 评论列表
     * </pre>
     */
    public Builder addNewsFollowList(NewsFollow value) {
      if (newsFollowListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewsFollowListIsMutable();
        newsFollowList_.add(value);
        onChanged();
      } else {
        newsFollowListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
     *
     * <pre>
     * 评论列表
     * </pre>
     */
    public Builder addNewsFollowList(
        int index, NewsFollow value) {
      if (newsFollowListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNewsFollowListIsMutable();
        newsFollowList_.add(index, value);
        onChanged();
      } else {
        newsFollowListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
     *
     * <pre>
     * 评论列表
     * </pre>
     */
    public Builder addNewsFollowList(
        NewsFollow.Builder builderForValue) {
      if (newsFollowListBuilder_ == null) {
        ensureNewsFollowListIsMutable();
        newsFollowList_.add(builderForValue.build());
        onChanged();
      } else {
        newsFollowListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
     *
     * <pre>
     * 评论列表
     * </pre>
     */
    public Builder addNewsFollowList(
        int index, NewsFollow.Builder builderForValue) {
      if (newsFollowListBuilder_ == null) {
        ensureNewsFollowListIsMutable();
        newsFollowList_.add(index, builderForValue.build());
        onChanged();
      } else {
        newsFollowListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
     *
     * <pre>
     * 评论列表
     * </pre>
     */
    public Builder addAllNewsFollowList(
        Iterable<? extends NewsFollow> values) {
      if (newsFollowListBuilder_ == null) {
        ensureNewsFollowListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, newsFollowList_);
        onChanged();
      } else {
        newsFollowListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
     *
     * <pre>
     * 评论列表
     * </pre>
     */
    public Builder clearNewsFollowList() {
      if (newsFollowListBuilder_ == null) {
        newsFollowList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        newsFollowListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
     *
     * <pre>
     * 评论列表
     * </pre>
     */
    public Builder removeNewsFollowList(int index) {
      if (newsFollowListBuilder_ == null) {
        ensureNewsFollowListIsMutable();
        newsFollowList_.remove(index);
        onChanged();
      } else {
        newsFollowListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
     *
     * <pre>
     * 评论列表
     * </pre>
     */
    public NewsFollow.Builder getNewsFollowListBuilder(
        int index) {
      return getNewsFollowListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
     *
     * <pre>
     * 评论列表
     * </pre>
     */
    public NewsFollowOrBuilder getNewsFollowListOrBuilder(
        int index) {
      if (newsFollowListBuilder_ == null) {
        return newsFollowList_.get(index);  } else {
        return newsFollowListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
     *
     * <pre>
     * 评论列表
     * </pre>
     */
    public java.util.List<? extends NewsFollowOrBuilder>
         getNewsFollowListOrBuilderList() {
      if (newsFollowListBuilder_ != null) {
        return newsFollowListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(newsFollowList_);
      }
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
     *
     * <pre>
     * 评论列表
     * </pre>
     */
    public NewsFollow.Builder addNewsFollowListBuilder() {
      return getNewsFollowListFieldBuilder().addBuilder(
          NewsFollow.getDefaultInstance());
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
     *
     * <pre>
     * 评论列表
     * </pre>
     */
    public NewsFollow.Builder addNewsFollowListBuilder(
        int index) {
      return getNewsFollowListFieldBuilder().addBuilder(
          index, NewsFollow.getDefaultInstance());
    }
    /**
     * <code>repeated .com.weiwuu.protobuf.NewsFollow newsFollowList = 5;</code>
     *
     * <pre>
     * 评论列表
     * </pre>
     */
    public java.util.List<NewsFollow.Builder>
         getNewsFollowListBuilderList() {
      return getNewsFollowListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        NewsFollow, NewsFollow.Builder, NewsFollowOrBuilder>
        getNewsFollowListFieldBuilder() {
      if (newsFollowListBuilder_ == null) {
        newsFollowListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            NewsFollow, NewsFollow.Builder, NewsFollowOrBuilder>(
                newsFollowList_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        newsFollowList_ = null;
      }
      return newsFollowListBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.weiwuu.protobuf.NewsList)
  }

  // @@protoc_insertion_point(class_scope:com.weiwuu.protobuf.NewsList)
  private static final NewsList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new NewsList();
  }

  public static NewsList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NewsList>
      PARSER = new com.google.protobuf.AbstractParser<NewsList>() {
    public NewsList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new NewsList(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<NewsList> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<NewsList> getParserForType() {
    return PARSER;
  }

  public NewsList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

