// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: News.proto

package com.weiwuu.protobuf;

public interface NewsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.weiwuu.protobuf.News)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   *
   * <pre>
   * ID
   * </pre>
   */
  int getId();

  /**
   * <code>optional string issueTime = 3;</code>
   *
   * <pre>
   * 发布时间:  (yyyy-MM-dd hh:mm:dd)
   * </pre>
   */
  String getIssueTime();
  /**
   * <code>optional string issueTime = 3;</code>
   *
   * <pre>
   * 发布时间:  (yyyy-MM-dd hh:mm:dd)
   * </pre>
   */
  com.google.protobuf.ByteString
      getIssueTimeBytes();

  /**
   * <code>optional int32 type1 = 4;</code>
   *
   * <pre>
   * 主要归类
   * </pre>
   */
  int getType1();

  /**
   * <code>optional int32 type2 = 5;</code>
   *
   * <pre>
   * 次要归类
   * </pre>
   */
  int getType2();

  /**
   * <code>optional int32 type3 = 6;</code>
   *
   * <pre>
   * 备选归类
   * </pre>
   */
  int getType3();

  /**
   * <code>optional string source = 10;</code>
   *
   * <pre>
   * 来源: (限制字数 &lt;= 64)
   * </pre>
   */
  String getSource();
  /**
   * <code>optional string source = 10;</code>
   *
   * <pre>
   * 来源: (限制字数 &lt;= 64)
   * </pre>
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <code>optional string sourceURL = 11;</code>
   */
  String getSourceURL();
  /**
   * <code>optional string sourceURL = 11;</code>
   */
  com.google.protobuf.ByteString
      getSourceURLBytes();

  /**
   * <code>optional string author = 12;</code>
   *
   * <pre>
   * 作者: (限制字数 &lt;= 64)
   * </pre>
   */
  String getAuthor();
  /**
   * <code>optional string author = 12;</code>
   *
   * <pre>
   * 作者: (限制字数 &lt;= 64)
   * </pre>
   */
  com.google.protobuf.ByteString
      getAuthorBytes();

  /**
   * <code>optional string authorURL = 13;</code>
   */
  String getAuthorURL();
  /**
   * <code>optional string authorURL = 13;</code>
   */
  com.google.protobuf.ByteString
      getAuthorURLBytes();

  /**
   * <code>optional string caption = 20;</code>
   *
   * <pre>
   * 标题: (限制字数 &lt;= 64)
   * </pre>
   */
  String getCaption();
  /**
   * <code>optional string caption = 20;</code>
   *
   * <pre>
   * 标题: (限制字数 &lt;= 64)
   * </pre>
   */
  com.google.protobuf.ByteString
      getCaptionBytes();

  /**
   * <code>optional string thumbURL = 21;</code>
   *
   * <pre>
   * 缩略图: (限制字数 &lt;= 256)
   * </pre>
   */
  String getThumbURL();
  /**
   * <code>optional string thumbURL = 21;</code>
   *
   * <pre>
   * 缩略图: (限制字数 &lt;= 256)
   * </pre>
   */
  com.google.protobuf.ByteString
      getThumbURLBytes();

  /**
   * <code>optional string figureURL = 22;</code>
   *
   * <pre>
   * 主配图: (限制字数 &lt;= 256)
   * </pre>
   */
  String getFigureURL();
  /**
   * <code>optional string figureURL = 22;</code>
   *
   * <pre>
   * 主配图: (限制字数 &lt;= 256)
   * </pre>
   */
  com.google.protobuf.ByteString
      getFigureURLBytes();

  /**
   * <code>optional string content = 23;</code>
   *
   * <pre>
   * 内容: (限制字数 &lt;= 4096)
   * </pre>
   */
  String getContent();
  /**
   * <code>optional string content = 23;</code>
   *
   * <pre>
   * 内容: (限制字数 &lt;= 4096)
   * </pre>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>optional string description = 24;</code>
   *
   * <pre>
   * 内容摘要: (限制字数 &lt;= 200)
   * </pre>
   */
  String getDescription();
  /**
   * <code>optional string description = 24;</code>
   *
   * <pre>
   * 内容摘要: (限制字数 &lt;= 200)
   * </pre>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>optional string shareDesc = 25;</code>
   *
   * <pre>
   * 分享描述: (限制字数 &lt;= 200)
   * </pre>
   */
  String getShareDesc();
  /**
   * <code>optional string shareDesc = 25;</code>
   *
   * <pre>
   * 分享描述: (限制字数 &lt;= 200)
   * </pre>
   */
  com.google.protobuf.ByteString
      getShareDescBytes();

  /**
   * <code>repeated int32 tagIds = 30;</code>
   *
   * <pre>
   * 相关标签清单
   * </pre>
   */
  java.util.List<Integer> getTagIdsList();
  /**
   * <code>repeated int32 tagIds = 30;</code>
   *
   * <pre>
   * 相关标签清单
   * </pre>
   */
  int getTagIdsCount();
  /**
   * <code>repeated int32 tagIds = 30;</code>
   *
   * <pre>
   * 相关标签清单
   * </pre>
   */
  int getTagIds(int index);

  /**
   * <code>repeated int32 topicIds = 31;</code>
   *
   * <pre>
   * 相关主题清单
   * </pre>
   */
  java.util.List<Integer> getTopicIdsList();
  /**
   * <code>repeated int32 topicIds = 31;</code>
   *
   * <pre>
   * 相关主题清单
   * </pre>
   */
  int getTopicIdsCount();
  /**
   * <code>repeated int32 topicIds = 31;</code>
   *
   * <pre>
   * 相关主题清单
   * </pre>
   */
  int getTopicIds(int index);

  /**
   * <code>repeated int32 relateIds = 32;</code>
   *
   * <pre>
   * 相关新闻清单
   * </pre>
   */
  java.util.List<Integer> getRelateIdsList();
  /**
   * <code>repeated int32 relateIds = 32;</code>
   *
   * <pre>
   * 相关新闻清单
   * </pre>
   */
  int getRelateIdsCount();
  /**
   * <code>repeated int32 relateIds = 32;</code>
   *
   * <pre>
   * 相关新闻清单
   * </pre>
   */
  int getRelateIds(int index);

  /**
   * <code>optional bool rotate = 40;</code>
   *
   * <pre>
   * 是否顶部轮播新闻   true:是，false：不是
   * </pre>
   */
  boolean getRotate();

  /**
   * <code>optional int32 cityId = 41;</code>
   *
   * <pre>
   * 所属城市ID
   * </pre>
   */
  int getCityId();
}
