// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewsStatistics.proto

package com.weiwuu.protobuf;

public final class NewsStatisticsProto {
  private NewsStatisticsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_weiwuu_protobuf_NewsStatistics_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_weiwuu_protobuf_NewsStatistics_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024NewsStatistics.proto\022\023com.weiwuu.proto" +
      "buf\"\240\001\n\016NewsStatistics\022\016\n\006newsId\030\001 \001(\005\022\023" +
      "\n\013followCount\030\002 \001(\005\022\023\n\013assentCount\030\003 \001(\005" +
      "\022\023\n\013opposeCount\030\004 \001(\005\022\023\n\013reportCount\030\005 \001" +
      "(\005\022\023\n\013sharedCount\030\006 \001(\005\022\025\n\rfavoriteCount" +
      "\030\007 \001(\005BR\n\023com.weiwuu.protobufB\023NewsStati" +
      "sticsProtoP\001\240\001\001\242\002\003WPB\252\002\032Weiwuu.Protobuf." +
      "KnownTypesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_weiwuu_protobuf_NewsStatistics_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_weiwuu_protobuf_NewsStatistics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_weiwuu_protobuf_NewsStatistics_descriptor,
        new String[] { "NewsId", "FollowCount", "AssentCount", "OpposeCount", "ReportCount", "SharedCount", "FavoriteCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
