// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: News.proto

package com.weiwuu.protobuf;

public final class NewsProto {
  private NewsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_weiwuu_protobuf_News_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_weiwuu_protobuf_News_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nNews.proto\022\023com.weiwuu.protobuf\"\334\002\n\004Ne" +
      "ws\022\n\n\002id\030\001 \001(\005\022\021\n\tissueTime\030\003 \001(\t\022\r\n\005typ" +
      "e1\030\004 \001(\005\022\r\n\005type2\030\005 \001(\005\022\r\n\005type3\030\006 \001(\005\022\016" +
      "\n\006source\030\n \001(\t\022\021\n\tsourceURL\030\013 \001(\t\022\016\n\006aut" +
      "hor\030\014 \001(\t\022\021\n\tauthorURL\030\r \001(\t\022\017\n\007caption\030" +
      "\024 \001(\t\022\020\n\010thumbURL\030\025 \001(\t\022\021\n\tfigureURL\030\026 \001" +
      "(\t\022\017\n\007content\030\027 \001(\t\022\023\n\013description\030\030 \001(\t" +
      "\022\021\n\tshareDesc\030\031 \001(\t\022\016\n\006tagIds\030\036 \003(\005\022\020\n\010t" +
      "opicIds\030\037 \003(\005\022\021\n\trelateIds\030  \003(\005\022\016\n\006rota" +
      "te\030( \001(\010\022\016\n\006cityId\030) \001(\005BH\n\023com.weiwuu.p",
      "rotobufB\tNewsProtoP\001\240\001\001\242\002\003WPB\252\002\032Weiwuu.P" +
      "rotobuf.KnownTypesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_weiwuu_protobuf_News_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_weiwuu_protobuf_News_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_weiwuu_protobuf_News_descriptor,
        new String[] { "Id", "IssueTime", "Type1", "Type2", "Type3", "Source", "SourceURL", "Author", "AuthorURL", "Caption", "ThumbURL", "FigureURL", "Content", "Description", "ShareDesc", "TagIds", "TopicIds", "RelateIds", "Rotate", "CityId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
