// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewsStatistics.proto

package com.weiwuu.protobuf;

/**
 * Protobuf type {@code com.weiwuu.protobuf.NewsStatistics}
 *
 * <pre>
 * 消息数据统计
 * </pre>
 */
public  final class NewsStatistics extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.weiwuu.protobuf.NewsStatistics)
    NewsStatisticsOrBuilder {
  // Use NewsStatistics.newBuilder() to construct.
  private NewsStatistics(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private NewsStatistics() {
    newsId_ = 0;
    followCount_ = 0;
    assentCount_ = 0;
    opposeCount_ = 0;
    reportCount_ = 0;
    sharedCount_ = 0;
    favoriteCount_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private NewsStatistics(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            newsId_ = input.readInt32();
            break;
          }
          case 16: {

            followCount_ = input.readInt32();
            break;
          }
          case 24: {

            assentCount_ = input.readInt32();
            break;
          }
          case 32: {

            opposeCount_ = input.readInt32();
            break;
          }
          case 40: {

            reportCount_ = input.readInt32();
            break;
          }
          case 48: {

            sharedCount_ = input.readInt32();
            break;
          }
          case 56: {

            favoriteCount_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return NewsStatisticsProto.internal_static_com_weiwuu_protobuf_NewsStatistics_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return NewsStatisticsProto.internal_static_com_weiwuu_protobuf_NewsStatistics_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            NewsStatistics.class, Builder.class);
  }

  public static final int NEWSID_FIELD_NUMBER = 1;
  private int newsId_;
  /**
   * <code>optional int32 newsId = 1;</code>
   *
   * <pre>
   * 消息ID
   * </pre>
   */
  public int getNewsId() {
    return newsId_;
  }

  public static final int FOLLOWCOUNT_FIELD_NUMBER = 2;
  private int followCount_;
  /**
   * <code>optional int32 followCount = 2;</code>
   *
   * <pre>
   * 跟帖统计
   * </pre>
   */
  public int getFollowCount() {
    return followCount_;
  }

  public static final int ASSENTCOUNT_FIELD_NUMBER = 3;
  private int assentCount_;
  /**
   * <code>optional int32 assentCount = 3;</code>
   *
   * <pre>
   * 赞同统计
   * </pre>
   */
  public int getAssentCount() {
    return assentCount_;
  }

  public static final int OPPOSECOUNT_FIELD_NUMBER = 4;
  private int opposeCount_;
  /**
   * <code>optional int32 opposeCount = 4;</code>
   *
   * <pre>
   * 反对统计
   * </pre>
   */
  public int getOpposeCount() {
    return opposeCount_;
  }

  public static final int REPORTCOUNT_FIELD_NUMBER = 5;
  private int reportCount_;
  /**
   * <code>optional int32 reportCount = 5;</code>
   *
   * <pre>
   * 举报统计
   * </pre>
   */
  public int getReportCount() {
    return reportCount_;
  }

  public static final int SHAREDCOUNT_FIELD_NUMBER = 6;
  private int sharedCount_;
  /**
   * <code>optional int32 sharedCount = 6;</code>
   *
   * <pre>
   * 分享统计
   * </pre>
   */
  public int getSharedCount() {
    return sharedCount_;
  }

  public static final int FAVORITECOUNT_FIELD_NUMBER = 7;
  private int favoriteCount_;
  /**
   * <code>optional int32 favoriteCount = 7;</code>
   *
   * <pre>
   * 收藏统计
   * </pre>
   */
  public int getFavoriteCount() {
    return favoriteCount_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (newsId_ != 0) {
      output.writeInt32(1, newsId_);
    }
    if (followCount_ != 0) {
      output.writeInt32(2, followCount_);
    }
    if (assentCount_ != 0) {
      output.writeInt32(3, assentCount_);
    }
    if (opposeCount_ != 0) {
      output.writeInt32(4, opposeCount_);
    }
    if (reportCount_ != 0) {
      output.writeInt32(5, reportCount_);
    }
    if (sharedCount_ != 0) {
      output.writeInt32(6, sharedCount_);
    }
    if (favoriteCount_ != 0) {
      output.writeInt32(7, favoriteCount_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (newsId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, newsId_);
    }
    if (followCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, followCount_);
    }
    if (assentCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, assentCount_);
    }
    if (opposeCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, opposeCount_);
    }
    if (reportCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, reportCount_);
    }
    if (sharedCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, sharedCount_);
    }
    if (favoriteCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, favoriteCount_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof NewsStatistics)) {
      return super.equals(obj);
    }
    NewsStatistics other = (NewsStatistics) obj;

    boolean result = true;
    result = result && (getNewsId()
        == other.getNewsId());
    result = result && (getFollowCount()
        == other.getFollowCount());
    result = result && (getAssentCount()
        == other.getAssentCount());
    result = result && (getOpposeCount()
        == other.getOpposeCount());
    result = result && (getReportCount()
        == other.getReportCount());
    result = result && (getSharedCount()
        == other.getSharedCount());
    result = result && (getFavoriteCount()
        == other.getFavoriteCount());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + NEWSID_FIELD_NUMBER;
    hash = (53 * hash) + getNewsId();
    hash = (37 * hash) + FOLLOWCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getFollowCount();
    hash = (37 * hash) + ASSENTCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getAssentCount();
    hash = (37 * hash) + OPPOSECOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getOpposeCount();
    hash = (37 * hash) + REPORTCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getReportCount();
    hash = (37 * hash) + SHAREDCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getSharedCount();
    hash = (37 * hash) + FAVORITECOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getFavoriteCount();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static NewsStatistics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NewsStatistics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NewsStatistics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NewsStatistics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NewsStatistics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static NewsStatistics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static NewsStatistics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static NewsStatistics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static NewsStatistics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static NewsStatistics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(NewsStatistics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.weiwuu.protobuf.NewsStatistics}
   *
   * <pre>
   * 消息数据统计
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.weiwuu.protobuf.NewsStatistics)
      NewsStatisticsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NewsStatisticsProto.internal_static_com_weiwuu_protobuf_NewsStatistics_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NewsStatisticsProto.internal_static_com_weiwuu_protobuf_NewsStatistics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NewsStatistics.class, Builder.class);
    }

    // Construct using com.weiwuu.protobuf.NewsStatistics.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      newsId_ = 0;

      followCount_ = 0;

      assentCount_ = 0;

      opposeCount_ = 0;

      reportCount_ = 0;

      sharedCount_ = 0;

      favoriteCount_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return NewsStatisticsProto.internal_static_com_weiwuu_protobuf_NewsStatistics_descriptor;
    }

    public NewsStatistics getDefaultInstanceForType() {
      return NewsStatistics.getDefaultInstance();
    }

    public NewsStatistics build() {
      NewsStatistics result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public NewsStatistics buildPartial() {
      NewsStatistics result = new NewsStatistics(this);
      result.newsId_ = newsId_;
      result.followCount_ = followCount_;
      result.assentCount_ = assentCount_;
      result.opposeCount_ = opposeCount_;
      result.reportCount_ = reportCount_;
      result.sharedCount_ = sharedCount_;
      result.favoriteCount_ = favoriteCount_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof NewsStatistics) {
        return mergeFrom((NewsStatistics)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(NewsStatistics other) {
      if (other == NewsStatistics.getDefaultInstance()) return this;
      if (other.getNewsId() != 0) {
        setNewsId(other.getNewsId());
      }
      if (other.getFollowCount() != 0) {
        setFollowCount(other.getFollowCount());
      }
      if (other.getAssentCount() != 0) {
        setAssentCount(other.getAssentCount());
      }
      if (other.getOpposeCount() != 0) {
        setOpposeCount(other.getOpposeCount());
      }
      if (other.getReportCount() != 0) {
        setReportCount(other.getReportCount());
      }
      if (other.getSharedCount() != 0) {
        setSharedCount(other.getSharedCount());
      }
      if (other.getFavoriteCount() != 0) {
        setFavoriteCount(other.getFavoriteCount());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      NewsStatistics parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (NewsStatistics) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int newsId_ ;
    /**
     * <code>optional int32 newsId = 1;</code>
     *
     * <pre>
     * 消息ID
     * </pre>
     */
    public int getNewsId() {
      return newsId_;
    }
    /**
     * <code>optional int32 newsId = 1;</code>
     *
     * <pre>
     * 消息ID
     * </pre>
     */
    public Builder setNewsId(int value) {
      
      newsId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 newsId = 1;</code>
     *
     * <pre>
     * 消息ID
     * </pre>
     */
    public Builder clearNewsId() {
      
      newsId_ = 0;
      onChanged();
      return this;
    }

    private int followCount_ ;
    /**
     * <code>optional int32 followCount = 2;</code>
     *
     * <pre>
     * 跟帖统计
     * </pre>
     */
    public int getFollowCount() {
      return followCount_;
    }
    /**
     * <code>optional int32 followCount = 2;</code>
     *
     * <pre>
     * 跟帖统计
     * </pre>
     */
    public Builder setFollowCount(int value) {
      
      followCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 followCount = 2;</code>
     *
     * <pre>
     * 跟帖统计
     * </pre>
     */
    public Builder clearFollowCount() {
      
      followCount_ = 0;
      onChanged();
      return this;
    }

    private int assentCount_ ;
    /**
     * <code>optional int32 assentCount = 3;</code>
     *
     * <pre>
     * 赞同统计
     * </pre>
     */
    public int getAssentCount() {
      return assentCount_;
    }
    /**
     * <code>optional int32 assentCount = 3;</code>
     *
     * <pre>
     * 赞同统计
     * </pre>
     */
    public Builder setAssentCount(int value) {
      
      assentCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 assentCount = 3;</code>
     *
     * <pre>
     * 赞同统计
     * </pre>
     */
    public Builder clearAssentCount() {
      
      assentCount_ = 0;
      onChanged();
      return this;
    }

    private int opposeCount_ ;
    /**
     * <code>optional int32 opposeCount = 4;</code>
     *
     * <pre>
     * 反对统计
     * </pre>
     */
    public int getOpposeCount() {
      return opposeCount_;
    }
    /**
     * <code>optional int32 opposeCount = 4;</code>
     *
     * <pre>
     * 反对统计
     * </pre>
     */
    public Builder setOpposeCount(int value) {
      
      opposeCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 opposeCount = 4;</code>
     *
     * <pre>
     * 反对统计
     * </pre>
     */
    public Builder clearOpposeCount() {
      
      opposeCount_ = 0;
      onChanged();
      return this;
    }

    private int reportCount_ ;
    /**
     * <code>optional int32 reportCount = 5;</code>
     *
     * <pre>
     * 举报统计
     * </pre>
     */
    public int getReportCount() {
      return reportCount_;
    }
    /**
     * <code>optional int32 reportCount = 5;</code>
     *
     * <pre>
     * 举报统计
     * </pre>
     */
    public Builder setReportCount(int value) {
      
      reportCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 reportCount = 5;</code>
     *
     * <pre>
     * 举报统计
     * </pre>
     */
    public Builder clearReportCount() {
      
      reportCount_ = 0;
      onChanged();
      return this;
    }

    private int sharedCount_ ;
    /**
     * <code>optional int32 sharedCount = 6;</code>
     *
     * <pre>
     * 分享统计
     * </pre>
     */
    public int getSharedCount() {
      return sharedCount_;
    }
    /**
     * <code>optional int32 sharedCount = 6;</code>
     *
     * <pre>
     * 分享统计
     * </pre>
     */
    public Builder setSharedCount(int value) {
      
      sharedCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 sharedCount = 6;</code>
     *
     * <pre>
     * 分享统计
     * </pre>
     */
    public Builder clearSharedCount() {
      
      sharedCount_ = 0;
      onChanged();
      return this;
    }

    private int favoriteCount_ ;
    /**
     * <code>optional int32 favoriteCount = 7;</code>
     *
     * <pre>
     * 收藏统计
     * </pre>
     */
    public int getFavoriteCount() {
      return favoriteCount_;
    }
    /**
     * <code>optional int32 favoriteCount = 7;</code>
     *
     * <pre>
     * 收藏统计
     * </pre>
     */
    public Builder setFavoriteCount(int value) {
      
      favoriteCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 favoriteCount = 7;</code>
     *
     * <pre>
     * 收藏统计
     * </pre>
     */
    public Builder clearFavoriteCount() {
      
      favoriteCount_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.weiwuu.protobuf.NewsStatistics)
  }

  // @@protoc_insertion_point(class_scope:com.weiwuu.protobuf.NewsStatistics)
  private static final NewsStatistics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new NewsStatistics();
  }

  public static NewsStatistics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NewsStatistics>
      PARSER = new com.google.protobuf.AbstractParser<NewsStatistics>() {
    public NewsStatistics parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new NewsStatistics(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<NewsStatistics> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<NewsStatistics> getParserForType() {
    return PARSER;
  }

  public NewsStatistics getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

