// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WXUser.proto

package com.weiwuu.protobuf;

/**
 * Protobuf type {@code com.weiwuu.protobuf.WXUser}
 *
 * <pre>
 * 微信用户信息
 * </pre>
 */
public  final class WXUser extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.weiwuu.protobuf.WXUser)
    WXUserOrBuilder {
  // Use WXUser.newBuilder() to construct.
  private WXUser(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private WXUser() {
    unionid_ = "";
    subscribe_ = 0;
    subscribeTime_ = "";
    nickname_ = "";
    sex_ = 0;
    country_ = "";
    province_ = "";
    city_ = "";
    languag_ = "";
    headImgUrl_ = "";
    remark_ = "";
    groupid_ = "";
    openId_ = "";
    userid_ = "";
    name_ = "";
    tel_ = "";
    type_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private WXUser(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            unionid_ = s;
            break;
          }
          case 16: {

            subscribe_ = input.readInt32();
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            subscribeTime_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            nickname_ = s;
            break;
          }
          case 40: {

            sex_ = input.readInt32();
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            country_ = s;
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            province_ = s;
            break;
          }
          case 66: {
            String s = input.readStringRequireUtf8();

            city_ = s;
            break;
          }
          case 74: {
            String s = input.readStringRequireUtf8();

            languag_ = s;
            break;
          }
          case 82: {
            String s = input.readStringRequireUtf8();

            headImgUrl_ = s;
            break;
          }
          case 90: {
            String s = input.readStringRequireUtf8();

            remark_ = s;
            break;
          }
          case 98: {
            String s = input.readStringRequireUtf8();

            groupid_ = s;
            break;
          }
          case 106: {
            String s = input.readStringRequireUtf8();

            openId_ = s;
            break;
          }
          case 114: {
            String s = input.readStringRequireUtf8();

            userid_ = s;
            break;
          }
          case 122: {
            String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 130: {
            String s = input.readStringRequireUtf8();

            tel_ = s;
            break;
          }
          case 168: {

            type_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return WXUserProto.internal_static_com_weiwuu_protobuf_WXUser_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return WXUserProto.internal_static_com_weiwuu_protobuf_WXUser_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            WXUser.class, Builder.class);
  }

  public static final int UNIONID_FIELD_NUMBER = 1;
  private volatile Object unionid_;
  /**
   * <code>optional string unionid = 1;</code>
   *
   * <pre>
   *unionid
   * </pre>
   */
  public String getUnionid() {
    Object ref = unionid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      unionid_ = s;
      return s;
    }
  }
  /**
   * <code>optional string unionid = 1;</code>
   *
   * <pre>
   *unionid
   * </pre>
   */
  public com.google.protobuf.ByteString
      getUnionidBytes() {
    Object ref = unionid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      unionid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBSCRIBE_FIELD_NUMBER = 2;
  private int subscribe_;
  /**
   * <code>optional int32 subscribe = 2;</code>
   *
   * <pre>
   * 关注状态
   * </pre>
   */
  public int getSubscribe() {
    return subscribe_;
  }

  public static final int SUBSCRIBETIME_FIELD_NUMBER = 3;
  private volatile Object subscribeTime_;
  /**
   * <code>optional string subscribeTime = 3;</code>
   *
   * <pre>
   * 关注时间
   * </pre>
   */
  public String getSubscribeTime() {
    Object ref = subscribeTime_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      subscribeTime_ = s;
      return s;
    }
  }
  /**
   * <code>optional string subscribeTime = 3;</code>
   *
   * <pre>
   * 关注时间
   * </pre>
   */
  public com.google.protobuf.ByteString
      getSubscribeTimeBytes() {
    Object ref = subscribeTime_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      subscribeTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NICKNAME_FIELD_NUMBER = 4;
  private volatile Object nickname_;
  /**
   * <code>optional string nickname = 4;</code>
   *
   * <pre>
   * 昵称
   * </pre>
   */
  public String getNickname() {
    Object ref = nickname_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      nickname_ = s;
      return s;
    }
  }
  /**
   * <code>optional string nickname = 4;</code>
   *
   * <pre>
   * 昵称
   * </pre>
   */
  public com.google.protobuf.ByteString
      getNicknameBytes() {
    Object ref = nickname_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      nickname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEX_FIELD_NUMBER = 5;
  private int sex_;
  /**
   * <code>optional int32 sex = 5;</code>
   *
   * <pre>
   * 性别 1男，2女，0未知
   * </pre>
   */
  public int getSex() {
    return sex_;
  }

  public static final int COUNTRY_FIELD_NUMBER = 6;
  private volatile Object country_;
  /**
   * <code>optional string country = 6;</code>
   *
   * <pre>
   * 所在国家
   * </pre>
   */
  public String getCountry() {
    Object ref = country_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      country_ = s;
      return s;
    }
  }
  /**
   * <code>optional string country = 6;</code>
   *
   * <pre>
   * 所在国家
   * </pre>
   */
  public com.google.protobuf.ByteString
      getCountryBytes() {
    Object ref = country_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      country_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROVINCE_FIELD_NUMBER = 7;
  private volatile Object province_;
  /**
   * <code>optional string province = 7;</code>
   *
   * <pre>
   * 所在省份
   * </pre>
   */
  public String getProvince() {
    Object ref = province_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      province_ = s;
      return s;
    }
  }
  /**
   * <code>optional string province = 7;</code>
   *
   * <pre>
   * 所在省份
   * </pre>
   */
  public com.google.protobuf.ByteString
      getProvinceBytes() {
    Object ref = province_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      province_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CITY_FIELD_NUMBER = 8;
  private volatile Object city_;
  /**
   * <code>optional string city = 8;</code>
   *
   * <pre>
   * 所在城市
   * </pre>
   */
  public String getCity() {
    Object ref = city_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      city_ = s;
      return s;
    }
  }
  /**
   * <code>optional string city = 8;</code>
   *
   * <pre>
   * 所在城市
   * </pre>
   */
  public com.google.protobuf.ByteString
      getCityBytes() {
    Object ref = city_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      city_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LANGUAG_FIELD_NUMBER = 9;
  private volatile Object languag_;
  /**
   * <code>optional string languag = 9;</code>
   *
   * <pre>
   * 用户的语言，简体中文为：zh_CN
   * </pre>
   */
  public String getLanguag() {
    Object ref = languag_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      languag_ = s;
      return s;
    }
  }
  /**
   * <code>optional string languag = 9;</code>
   *
   * <pre>
   * 用户的语言，简体中文为：zh_CN
   * </pre>
   */
  public com.google.protobuf.ByteString
      getLanguagBytes() {
    Object ref = languag_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      languag_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HEADIMGURL_FIELD_NUMBER = 10;
  private volatile Object headImgUrl_;
  /**
   * <code>optional string headImgUrl = 10;</code>
   *
   * <pre>
   * 用户头像
   * </pre>
   */
  public String getHeadImgUrl() {
    Object ref = headImgUrl_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      headImgUrl_ = s;
      return s;
    }
  }
  /**
   * <code>optional string headImgUrl = 10;</code>
   *
   * <pre>
   * 用户头像
   * </pre>
   */
  public com.google.protobuf.ByteString
      getHeadImgUrlBytes() {
    Object ref = headImgUrl_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      headImgUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REMARK_FIELD_NUMBER = 11;
  private volatile Object remark_;
  /**
   * <code>optional string remark = 11;</code>
   *
   * <pre>
   * 备注
   * </pre>
   */
  public String getRemark() {
    Object ref = remark_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      remark_ = s;
      return s;
    }
  }
  /**
   * <code>optional string remark = 11;</code>
   *
   * <pre>
   * 备注
   * </pre>
   */
  public com.google.protobuf.ByteString
      getRemarkBytes() {
    Object ref = remark_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      remark_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GROUPID_FIELD_NUMBER = 12;
  private volatile Object groupid_;
  /**
   * <code>optional string groupid = 12;</code>
   *
   * <pre>
   * 所在分组ID
   * </pre>
   */
  public String getGroupid() {
    Object ref = groupid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      groupid_ = s;
      return s;
    }
  }
  /**
   * <code>optional string groupid = 12;</code>
   *
   * <pre>
   * 所在分组ID
   * </pre>
   */
  public com.google.protobuf.ByteString
      getGroupidBytes() {
    Object ref = groupid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      groupid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPENID_FIELD_NUMBER = 13;
  private volatile Object openId_;
  /**
   * <code>optional string openId = 13;</code>
   *
   * <pre>
   * 每个公众号下用户的标识
   * </pre>
   */
  public String getOpenId() {
    Object ref = openId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      openId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string openId = 13;</code>
   *
   * <pre>
   * 每个公众号下用户的标识
   * </pre>
   */
  public com.google.protobuf.ByteString
      getOpenIdBytes() {
    Object ref = openId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      openId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERID_FIELD_NUMBER = 14;
  private volatile Object userid_;
  /**
   * <code>optional string userid = 14;</code>
   *
   * <pre>
   *userid
   * </pre>
   */
  public String getUserid() {
    Object ref = userid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      userid_ = s;
      return s;
    }
  }
  /**
   * <code>optional string userid = 14;</code>
   *
   * <pre>
   *userid
   * </pre>
   */
  public com.google.protobuf.ByteString
      getUseridBytes() {
    Object ref = userid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      userid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 15;
  private volatile Object name_;
  /**
   * <code>optional string name = 15;</code>
   *
   * <pre>
   *用户姓名
   * </pre>
   */
  public String getName() {
    Object ref = name_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 15;</code>
   *
   * <pre>
   *用户姓名
   * </pre>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    Object ref = name_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEL_FIELD_NUMBER = 16;
  private volatile Object tel_;
  /**
   * <code>optional string tel = 16;</code>
   *
   * <pre>
   *用户电话
   * </pre>
   */
  public String getTel() {
    Object ref = tel_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      tel_ = s;
      return s;
    }
  }
  /**
   * <code>optional string tel = 16;</code>
   *
   * <pre>
   *用户电话
   * </pre>
   */
  public com.google.protobuf.ByteString
      getTelBytes() {
    Object ref = tel_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      tel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 21;
  private int type_;
  /**
   * <code>optional int32 type = 21;</code>
   *
   * <pre>
   *用户类型：1：买房人；2：帮帮
   * </pre>
   */
  public int getType() {
    return type_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUnionidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, unionid_);
    }
    if (subscribe_ != 0) {
      output.writeInt32(2, subscribe_);
    }
    if (!getSubscribeTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, subscribeTime_);
    }
    if (!getNicknameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, nickname_);
    }
    if (sex_ != 0) {
      output.writeInt32(5, sex_);
    }
    if (!getCountryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, country_);
    }
    if (!getProvinceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, province_);
    }
    if (!getCityBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, city_);
    }
    if (!getLanguagBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, languag_);
    }
    if (!getHeadImgUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, headImgUrl_);
    }
    if (!getRemarkBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 11, remark_);
    }
    if (!getGroupidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 12, groupid_);
    }
    if (!getOpenIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 13, openId_);
    }
    if (!getUseridBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 14, userid_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 15, name_);
    }
    if (!getTelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 16, tel_);
    }
    if (type_ != 0) {
      output.writeInt32(21, type_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUnionidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, unionid_);
    }
    if (subscribe_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, subscribe_);
    }
    if (!getSubscribeTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, subscribeTime_);
    }
    if (!getNicknameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, nickname_);
    }
    if (sex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, sex_);
    }
    if (!getCountryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, country_);
    }
    if (!getProvinceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, province_);
    }
    if (!getCityBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, city_);
    }
    if (!getLanguagBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, languag_);
    }
    if (!getHeadImgUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, headImgUrl_);
    }
    if (!getRemarkBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(11, remark_);
    }
    if (!getGroupidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(12, groupid_);
    }
    if (!getOpenIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(13, openId_);
    }
    if (!getUseridBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(14, userid_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(15, name_);
    }
    if (!getTelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(16, tel_);
    }
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(21, type_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof WXUser)) {
      return super.equals(obj);
    }
    WXUser other = (WXUser) obj;

    boolean result = true;
    result = result && getUnionid()
        .equals(other.getUnionid());
    result = result && (getSubscribe()
        == other.getSubscribe());
    result = result && getSubscribeTime()
        .equals(other.getSubscribeTime());
    result = result && getNickname()
        .equals(other.getNickname());
    result = result && (getSex()
        == other.getSex());
    result = result && getCountry()
        .equals(other.getCountry());
    result = result && getProvince()
        .equals(other.getProvince());
    result = result && getCity()
        .equals(other.getCity());
    result = result && getLanguag()
        .equals(other.getLanguag());
    result = result && getHeadImgUrl()
        .equals(other.getHeadImgUrl());
    result = result && getRemark()
        .equals(other.getRemark());
    result = result && getGroupid()
        .equals(other.getGroupid());
    result = result && getOpenId()
        .equals(other.getOpenId());
    result = result && getUserid()
        .equals(other.getUserid());
    result = result && getName()
        .equals(other.getName());
    result = result && getTel()
        .equals(other.getTel());
    result = result && (getType()
        == other.getType());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + UNIONID_FIELD_NUMBER;
    hash = (53 * hash) + getUnionid().hashCode();
    hash = (37 * hash) + SUBSCRIBE_FIELD_NUMBER;
    hash = (53 * hash) + getSubscribe();
    hash = (37 * hash) + SUBSCRIBETIME_FIELD_NUMBER;
    hash = (53 * hash) + getSubscribeTime().hashCode();
    hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
    hash = (53 * hash) + getNickname().hashCode();
    hash = (37 * hash) + SEX_FIELD_NUMBER;
    hash = (53 * hash) + getSex();
    hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
    hash = (53 * hash) + getCountry().hashCode();
    hash = (37 * hash) + PROVINCE_FIELD_NUMBER;
    hash = (53 * hash) + getProvince().hashCode();
    hash = (37 * hash) + CITY_FIELD_NUMBER;
    hash = (53 * hash) + getCity().hashCode();
    hash = (37 * hash) + LANGUAG_FIELD_NUMBER;
    hash = (53 * hash) + getLanguag().hashCode();
    hash = (37 * hash) + HEADIMGURL_FIELD_NUMBER;
    hash = (53 * hash) + getHeadImgUrl().hashCode();
    hash = (37 * hash) + REMARK_FIELD_NUMBER;
    hash = (53 * hash) + getRemark().hashCode();
    hash = (37 * hash) + GROUPID_FIELD_NUMBER;
    hash = (53 * hash) + getGroupid().hashCode();
    hash = (37 * hash) + OPENID_FIELD_NUMBER;
    hash = (53 * hash) + getOpenId().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserid().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + TEL_FIELD_NUMBER;
    hash = (53 * hash) + getTel().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static WXUser parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static WXUser parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static WXUser parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static WXUser parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static WXUser parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static WXUser parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static WXUser parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static WXUser parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static WXUser parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static WXUser parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(WXUser prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.weiwuu.protobuf.WXUser}
   *
   * <pre>
   * 微信用户信息
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.weiwuu.protobuf.WXUser)
      WXUserOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return WXUserProto.internal_static_com_weiwuu_protobuf_WXUser_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return WXUserProto.internal_static_com_weiwuu_protobuf_WXUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              WXUser.class, Builder.class);
    }

    // Construct using com.weiwuu.protobuf.WXUser.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      unionid_ = "";

      subscribe_ = 0;

      subscribeTime_ = "";

      nickname_ = "";

      sex_ = 0;

      country_ = "";

      province_ = "";

      city_ = "";

      languag_ = "";

      headImgUrl_ = "";

      remark_ = "";

      groupid_ = "";

      openId_ = "";

      userid_ = "";

      name_ = "";

      tel_ = "";

      type_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return WXUserProto.internal_static_com_weiwuu_protobuf_WXUser_descriptor;
    }

    public WXUser getDefaultInstanceForType() {
      return WXUser.getDefaultInstance();
    }

    public WXUser build() {
      WXUser result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public WXUser buildPartial() {
      WXUser result = new WXUser(this);
      result.unionid_ = unionid_;
      result.subscribe_ = subscribe_;
      result.subscribeTime_ = subscribeTime_;
      result.nickname_ = nickname_;
      result.sex_ = sex_;
      result.country_ = country_;
      result.province_ = province_;
      result.city_ = city_;
      result.languag_ = languag_;
      result.headImgUrl_ = headImgUrl_;
      result.remark_ = remark_;
      result.groupid_ = groupid_;
      result.openId_ = openId_;
      result.userid_ = userid_;
      result.name_ = name_;
      result.tel_ = tel_;
      result.type_ = type_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof WXUser) {
        return mergeFrom((WXUser)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(WXUser other) {
      if (other == WXUser.getDefaultInstance()) return this;
      if (!other.getUnionid().isEmpty()) {
        unionid_ = other.unionid_;
        onChanged();
      }
      if (other.getSubscribe() != 0) {
        setSubscribe(other.getSubscribe());
      }
      if (!other.getSubscribeTime().isEmpty()) {
        subscribeTime_ = other.subscribeTime_;
        onChanged();
      }
      if (!other.getNickname().isEmpty()) {
        nickname_ = other.nickname_;
        onChanged();
      }
      if (other.getSex() != 0) {
        setSex(other.getSex());
      }
      if (!other.getCountry().isEmpty()) {
        country_ = other.country_;
        onChanged();
      }
      if (!other.getProvince().isEmpty()) {
        province_ = other.province_;
        onChanged();
      }
      if (!other.getCity().isEmpty()) {
        city_ = other.city_;
        onChanged();
      }
      if (!other.getLanguag().isEmpty()) {
        languag_ = other.languag_;
        onChanged();
      }
      if (!other.getHeadImgUrl().isEmpty()) {
        headImgUrl_ = other.headImgUrl_;
        onChanged();
      }
      if (!other.getRemark().isEmpty()) {
        remark_ = other.remark_;
        onChanged();
      }
      if (!other.getGroupid().isEmpty()) {
        groupid_ = other.groupid_;
        onChanged();
      }
      if (!other.getOpenId().isEmpty()) {
        openId_ = other.openId_;
        onChanged();
      }
      if (!other.getUserid().isEmpty()) {
        userid_ = other.userid_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getTel().isEmpty()) {
        tel_ = other.tel_;
        onChanged();
      }
      if (other.getType() != 0) {
        setType(other.getType());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      WXUser parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (WXUser) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object unionid_ = "";
    /**
     * <code>optional string unionid = 1;</code>
     *
     * <pre>
     *unionid
     * </pre>
     */
    public String getUnionid() {
      Object ref = unionid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        unionid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string unionid = 1;</code>
     *
     * <pre>
     *unionid
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUnionidBytes() {
      Object ref = unionid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        unionid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string unionid = 1;</code>
     *
     * <pre>
     *unionid
     * </pre>
     */
    public Builder setUnionid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      unionid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string unionid = 1;</code>
     *
     * <pre>
     *unionid
     * </pre>
     */
    public Builder clearUnionid() {
      
      unionid_ = getDefaultInstance().getUnionid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string unionid = 1;</code>
     *
     * <pre>
     *unionid
     * </pre>
     */
    public Builder setUnionidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      unionid_ = value;
      onChanged();
      return this;
    }

    private int subscribe_ ;
    /**
     * <code>optional int32 subscribe = 2;</code>
     *
     * <pre>
     * 关注状态
     * </pre>
     */
    public int getSubscribe() {
      return subscribe_;
    }
    /**
     * <code>optional int32 subscribe = 2;</code>
     *
     * <pre>
     * 关注状态
     * </pre>
     */
    public Builder setSubscribe(int value) {
      
      subscribe_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 subscribe = 2;</code>
     *
     * <pre>
     * 关注状态
     * </pre>
     */
    public Builder clearSubscribe() {
      
      subscribe_ = 0;
      onChanged();
      return this;
    }

    private Object subscribeTime_ = "";
    /**
     * <code>optional string subscribeTime = 3;</code>
     *
     * <pre>
     * 关注时间
     * </pre>
     */
    public String getSubscribeTime() {
      Object ref = subscribeTime_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        subscribeTime_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string subscribeTime = 3;</code>
     *
     * <pre>
     * 关注时间
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSubscribeTimeBytes() {
      Object ref = subscribeTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        subscribeTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string subscribeTime = 3;</code>
     *
     * <pre>
     * 关注时间
     * </pre>
     */
    public Builder setSubscribeTime(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      subscribeTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string subscribeTime = 3;</code>
     *
     * <pre>
     * 关注时间
     * </pre>
     */
    public Builder clearSubscribeTime() {
      
      subscribeTime_ = getDefaultInstance().getSubscribeTime();
      onChanged();
      return this;
    }
    /**
     * <code>optional string subscribeTime = 3;</code>
     *
     * <pre>
     * 关注时间
     * </pre>
     */
    public Builder setSubscribeTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      subscribeTime_ = value;
      onChanged();
      return this;
    }

    private Object nickname_ = "";
    /**
     * <code>optional string nickname = 4;</code>
     *
     * <pre>
     * 昵称
     * </pre>
     */
    public String getNickname() {
      Object ref = nickname_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nickname_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string nickname = 4;</code>
     *
     * <pre>
     * 昵称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      Object ref = nickname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string nickname = 4;</code>
     *
     * <pre>
     * 昵称
     * </pre>
     */
    public Builder setNickname(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nickname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string nickname = 4;</code>
     *
     * <pre>
     * 昵称
     * </pre>
     */
    public Builder clearNickname() {
      
      nickname_ = getDefaultInstance().getNickname();
      onChanged();
      return this;
    }
    /**
     * <code>optional string nickname = 4;</code>
     *
     * <pre>
     * 昵称
     * </pre>
     */
    public Builder setNicknameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nickname_ = value;
      onChanged();
      return this;
    }

    private int sex_ ;
    /**
     * <code>optional int32 sex = 5;</code>
     *
     * <pre>
     * 性别 1男，2女，0未知
     * </pre>
     */
    public int getSex() {
      return sex_;
    }
    /**
     * <code>optional int32 sex = 5;</code>
     *
     * <pre>
     * 性别 1男，2女，0未知
     * </pre>
     */
    public Builder setSex(int value) {
      
      sex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 sex = 5;</code>
     *
     * <pre>
     * 性别 1男，2女，0未知
     * </pre>
     */
    public Builder clearSex() {
      
      sex_ = 0;
      onChanged();
      return this;
    }

    private Object country_ = "";
    /**
     * <code>optional string country = 6;</code>
     *
     * <pre>
     * 所在国家
     * </pre>
     */
    public String getCountry() {
      Object ref = country_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        country_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string country = 6;</code>
     *
     * <pre>
     * 所在国家
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      Object ref = country_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string country = 6;</code>
     *
     * <pre>
     * 所在国家
     * </pre>
     */
    public Builder setCountry(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      country_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string country = 6;</code>
     *
     * <pre>
     * 所在国家
     * </pre>
     */
    public Builder clearCountry() {
      
      country_ = getDefaultInstance().getCountry();
      onChanged();
      return this;
    }
    /**
     * <code>optional string country = 6;</code>
     *
     * <pre>
     * 所在国家
     * </pre>
     */
    public Builder setCountryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      country_ = value;
      onChanged();
      return this;
    }

    private Object province_ = "";
    /**
     * <code>optional string province = 7;</code>
     *
     * <pre>
     * 所在省份
     * </pre>
     */
    public String getProvince() {
      Object ref = province_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        province_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string province = 7;</code>
     *
     * <pre>
     * 所在省份
     * </pre>
     */
    public com.google.protobuf.ByteString
        getProvinceBytes() {
      Object ref = province_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        province_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string province = 7;</code>
     *
     * <pre>
     * 所在省份
     * </pre>
     */
    public Builder setProvince(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      province_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string province = 7;</code>
     *
     * <pre>
     * 所在省份
     * </pre>
     */
    public Builder clearProvince() {
      
      province_ = getDefaultInstance().getProvince();
      onChanged();
      return this;
    }
    /**
     * <code>optional string province = 7;</code>
     *
     * <pre>
     * 所在省份
     * </pre>
     */
    public Builder setProvinceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      province_ = value;
      onChanged();
      return this;
    }

    private Object city_ = "";
    /**
     * <code>optional string city = 8;</code>
     *
     * <pre>
     * 所在城市
     * </pre>
     */
    public String getCity() {
      Object ref = city_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        city_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string city = 8;</code>
     *
     * <pre>
     * 所在城市
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string city = 8;</code>
     *
     * <pre>
     * 所在城市
     * </pre>
     */
    public Builder setCity(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      city_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string city = 8;</code>
     *
     * <pre>
     * 所在城市
     * </pre>
     */
    public Builder clearCity() {
      
      city_ = getDefaultInstance().getCity();
      onChanged();
      return this;
    }
    /**
     * <code>optional string city = 8;</code>
     *
     * <pre>
     * 所在城市
     * </pre>
     */
    public Builder setCityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      city_ = value;
      onChanged();
      return this;
    }

    private Object languag_ = "";
    /**
     * <code>optional string languag = 9;</code>
     *
     * <pre>
     * 用户的语言，简体中文为：zh_CN
     * </pre>
     */
    public String getLanguag() {
      Object ref = languag_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        languag_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string languag = 9;</code>
     *
     * <pre>
     * 用户的语言，简体中文为：zh_CN
     * </pre>
     */
    public com.google.protobuf.ByteString
        getLanguagBytes() {
      Object ref = languag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        languag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string languag = 9;</code>
     *
     * <pre>
     * 用户的语言，简体中文为：zh_CN
     * </pre>
     */
    public Builder setLanguag(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      languag_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string languag = 9;</code>
     *
     * <pre>
     * 用户的语言，简体中文为：zh_CN
     * </pre>
     */
    public Builder clearLanguag() {
      
      languag_ = getDefaultInstance().getLanguag();
      onChanged();
      return this;
    }
    /**
     * <code>optional string languag = 9;</code>
     *
     * <pre>
     * 用户的语言，简体中文为：zh_CN
     * </pre>
     */
    public Builder setLanguagBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      languag_ = value;
      onChanged();
      return this;
    }

    private Object headImgUrl_ = "";
    /**
     * <code>optional string headImgUrl = 10;</code>
     *
     * <pre>
     * 用户头像
     * </pre>
     */
    public String getHeadImgUrl() {
      Object ref = headImgUrl_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        headImgUrl_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string headImgUrl = 10;</code>
     *
     * <pre>
     * 用户头像
     * </pre>
     */
    public com.google.protobuf.ByteString
        getHeadImgUrlBytes() {
      Object ref = headImgUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        headImgUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string headImgUrl = 10;</code>
     *
     * <pre>
     * 用户头像
     * </pre>
     */
    public Builder setHeadImgUrl(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      headImgUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string headImgUrl = 10;</code>
     *
     * <pre>
     * 用户头像
     * </pre>
     */
    public Builder clearHeadImgUrl() {
      
      headImgUrl_ = getDefaultInstance().getHeadImgUrl();
      onChanged();
      return this;
    }
    /**
     * <code>optional string headImgUrl = 10;</code>
     *
     * <pre>
     * 用户头像
     * </pre>
     */
    public Builder setHeadImgUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      headImgUrl_ = value;
      onChanged();
      return this;
    }

    private Object remark_ = "";
    /**
     * <code>optional string remark = 11;</code>
     *
     * <pre>
     * 备注
     * </pre>
     */
    public String getRemark() {
      Object ref = remark_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        remark_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string remark = 11;</code>
     *
     * <pre>
     * 备注
     * </pre>
     */
    public com.google.protobuf.ByteString
        getRemarkBytes() {
      Object ref = remark_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string remark = 11;</code>
     *
     * <pre>
     * 备注
     * </pre>
     */
    public Builder setRemark(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      remark_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string remark = 11;</code>
     *
     * <pre>
     * 备注
     * </pre>
     */
    public Builder clearRemark() {
      
      remark_ = getDefaultInstance().getRemark();
      onChanged();
      return this;
    }
    /**
     * <code>optional string remark = 11;</code>
     *
     * <pre>
     * 备注
     * </pre>
     */
    public Builder setRemarkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      remark_ = value;
      onChanged();
      return this;
    }

    private Object groupid_ = "";
    /**
     * <code>optional string groupid = 12;</code>
     *
     * <pre>
     * 所在分组ID
     * </pre>
     */
    public String getGroupid() {
      Object ref = groupid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        groupid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string groupid = 12;</code>
     *
     * <pre>
     * 所在分组ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getGroupidBytes() {
      Object ref = groupid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        groupid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string groupid = 12;</code>
     *
     * <pre>
     * 所在分组ID
     * </pre>
     */
    public Builder setGroupid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      groupid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string groupid = 12;</code>
     *
     * <pre>
     * 所在分组ID
     * </pre>
     */
    public Builder clearGroupid() {
      
      groupid_ = getDefaultInstance().getGroupid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string groupid = 12;</code>
     *
     * <pre>
     * 所在分组ID
     * </pre>
     */
    public Builder setGroupidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      groupid_ = value;
      onChanged();
      return this;
    }

    private Object openId_ = "";
    /**
     * <code>optional string openId = 13;</code>
     *
     * <pre>
     * 每个公众号下用户的标识
     * </pre>
     */
    public String getOpenId() {
      Object ref = openId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        openId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string openId = 13;</code>
     *
     * <pre>
     * 每个公众号下用户的标识
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOpenIdBytes() {
      Object ref = openId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        openId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string openId = 13;</code>
     *
     * <pre>
     * 每个公众号下用户的标识
     * </pre>
     */
    public Builder setOpenId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      openId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string openId = 13;</code>
     *
     * <pre>
     * 每个公众号下用户的标识
     * </pre>
     */
    public Builder clearOpenId() {
      
      openId_ = getDefaultInstance().getOpenId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string openId = 13;</code>
     *
     * <pre>
     * 每个公众号下用户的标识
     * </pre>
     */
    public Builder setOpenIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      openId_ = value;
      onChanged();
      return this;
    }

    private Object userid_ = "";
    /**
     * <code>optional string userid = 14;</code>
     *
     * <pre>
     *userid
     * </pre>
     */
    public String getUserid() {
      Object ref = userid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string userid = 14;</code>
     *
     * <pre>
     *userid
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUseridBytes() {
      Object ref = userid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string userid = 14;</code>
     *
     * <pre>
     *userid
     * </pre>
     */
    public Builder setUserid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string userid = 14;</code>
     *
     * <pre>
     *userid
     * </pre>
     */
    public Builder clearUserid() {
      
      userid_ = getDefaultInstance().getUserid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string userid = 14;</code>
     *
     * <pre>
     *userid
     * </pre>
     */
    public Builder setUseridBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userid_ = value;
      onChanged();
      return this;
    }

    private Object name_ = "";
    /**
     * <code>optional string name = 15;</code>
     *
     * <pre>
     *用户姓名
     * </pre>
     */
    public String getName() {
      Object ref = name_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string name = 15;</code>
     *
     * <pre>
     *用户姓名
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 15;</code>
     *
     * <pre>
     *用户姓名
     * </pre>
     */
    public Builder setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 15;</code>
     *
     * <pre>
     *用户姓名
     * </pre>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 15;</code>
     *
     * <pre>
     *用户姓名
     * </pre>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private Object tel_ = "";
    /**
     * <code>optional string tel = 16;</code>
     *
     * <pre>
     *用户电话
     * </pre>
     */
    public String getTel() {
      Object ref = tel_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tel_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string tel = 16;</code>
     *
     * <pre>
     *用户电话
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTelBytes() {
      Object ref = tel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string tel = 16;</code>
     *
     * <pre>
     *用户电话
     * </pre>
     */
    public Builder setTel(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string tel = 16;</code>
     *
     * <pre>
     *用户电话
     * </pre>
     */
    public Builder clearTel() {
      
      tel_ = getDefaultInstance().getTel();
      onChanged();
      return this;
    }
    /**
     * <code>optional string tel = 16;</code>
     *
     * <pre>
     *用户电话
     * </pre>
     */
    public Builder setTelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tel_ = value;
      onChanged();
      return this;
    }

    private int type_ ;
    /**
     * <code>optional int32 type = 21;</code>
     *
     * <pre>
     *用户类型：1：买房人；2：帮帮
     * </pre>
     */
    public int getType() {
      return type_;
    }
    /**
     * <code>optional int32 type = 21;</code>
     *
     * <pre>
     *用户类型：1：买房人；2：帮帮
     * </pre>
     */
    public Builder setType(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 type = 21;</code>
     *
     * <pre>
     *用户类型：1：买房人；2：帮帮
     * </pre>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.weiwuu.protobuf.WXUser)
  }

  // @@protoc_insertion_point(class_scope:com.weiwuu.protobuf.WXUser)
  private static final WXUser DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new WXUser();
  }

  public static WXUser getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WXUser>
      PARSER = new com.google.protobuf.AbstractParser<WXUser>() {
    public WXUser parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new WXUser(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<WXUser> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<WXUser> getParserForType() {
    return PARSER;
  }

  public WXUser getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

