// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WXUser.proto

package com.weiwuu.protobuf;

public final class WXUserProto {
  private WXUserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_weiwuu_protobuf_WXUser_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_weiwuu_protobuf_WXUser_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014WXUser.proto\022\023com.weiwuu.protobuf\"\242\002\n\006" +
      "WXUser\022\017\n\007unionid\030\001 \001(\t\022\021\n\tsubscribe\030\002 \001" +
      "(\005\022\025\n\rsubscribeTime\030\003 \001(\t\022\020\n\010nickname\030\004 " +
      "\001(\t\022\013\n\003sex\030\005 \001(\005\022\017\n\007country\030\006 \001(\t\022\020\n\010pro" +
      "vince\030\007 \001(\t\022\014\n\004city\030\010 \001(\t\022\017\n\007languag\030\t \001" +
      "(\t\022\022\n\nheadImgUrl\030\n \001(\t\022\016\n\006remark\030\013 \001(\t\022\017" +
      "\n\007groupid\030\014 \001(\t\022\016\n\006openId\030\r \001(\t\022\016\n\006useri" +
      "d\030\016 \001(\t\022\014\n\004name\030\017 \001(\t\022\013\n\003tel\030\020 \001(\t\022\014\n\004ty" +
      "pe\030\025 \001(\005BJ\n\023com.weiwuu.protobufB\013WXUserP" +
      "rotoP\001\240\001\001\242\002\003WPB\252\002\032Weiwuu.Protobuf.KnownT",
      "ypesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_weiwuu_protobuf_WXUser_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_weiwuu_protobuf_WXUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_weiwuu_protobuf_WXUser_descriptor,
        new String[] { "Unionid", "Subscribe", "SubscribeTime", "Nickname", "Sex", "Country", "Province", "City", "Languag", "HeadImgUrl", "Remark", "Groupid", "OpenId", "Userid", "Name", "Tel", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
